### PR TITLE
[Incubator kie issues#2260]  Fix tests in tck due to failure in implicit conversion of Date Time

### LINKED ISSUE #2260: Error in TCK tests due to failure in implicit conversion of Date Time
The below mentioned testcases introduced by the PR [https://github.com/dmn-tck/tck/pull/717] fails. This ticket focuses on identifying the root cause of these and fixing them.
```
<testCase id="010">
        <resultNode name="Implicit Conversions CE" type="decision">
            <expected>
                <list>
                    <item>
                        <list>
                            <item>
                                <value xsi:type="xsd:decimal">1</value>
                            </item>
                        </list>
                    </item>
                    <item>
                        <value xsi:type="xsd:decimal">2</value>
                    </item>
                    <item>
                        <value xsi:type="xsd:dateTime">2000-12-01T00:00:00Z</value>
                    </item>
                </list>
            </expected>
        </resultNode>
    </testCase>

    <testCase id="011">
        <resultNode name="Implicit Conversions FUNCT" type="decision">
            <expected>
                <list>
                    <item>
                        <list>
                            <item>
                                <value xsi:type="xsd:decimal">1</value>
                            </item>
                        </list>
                    </item>
                    <item>
                        <value xsi:type="xsd:decimal">2</value>
                    </item>
                    <item>
                        <value xsi:type="xsd:dateTime">2000-02-01T00:00:00Z</value>
                    </item>
                </list>
            </expected>
        </resultNode>
    </testCase>
```

The expected result is *[[1], 2, 2000-12-01T00:00:00Z]* but what we get is *[[1], 2, 2000-12-01T00:00Z]*
For the DateTime type we apply the below logic and the seconds value is getting truncated.

```
public static ZonedDateTime coerceDateTime(final LocalDate value) {
        return ZonedDateTime.of(value, LocalTime.of(0, 0, 0, 0), ZoneOffset.UTC);
}
```
**Errors:** 
[ERROR]   ERROR: FAILURE: 'Implicit Conversions CE' expected='[[1], 2, 2000-12-01T00:00:00Z]' but found='[[1], 2, 2000-12-01T00:00Z]'
[ERROR]   ERROR: FAILURE: 'Implicit Conversions FUNCT' expected='[[1], 2, 2000-02-01T00:00:00Z]' but found='[[1], 2, 2000-02-01T00:00Z]'

### PR DESCRIPTION
**Pull request by AthiraHari77**
Closes :  https://github.com/apache/incubator-kie-issues/issues/2260

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

### CODE REVIEW

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/custom/FormattedZonedDateTime.java [hunk 1]
```diff
@@ -0,0 +1,193 @@
...
+import java.time.temporal.TemporalAccessor;
+import java.time.temporal.TemporalAmount;
+import java.time.temporal.TemporalField;
+import java.time.temporal.TemporalUnit;
+import java.util.Objects;
+
+/**
+ * This class is meant as sort-of <b>decorator</b> over <code>ZonedDateTime</code>, that is a final class.
+ * It is used to provide a string representation that preserves seconds even when they are zero,
+ */
```
Comment (yesamer) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/custom/FormattedZonedDateTime.java:56]: @AthiraHari77 Can you please provide in this description the precise points in which `ZonedDateTime` differs with `CustomZonedDateTime`?

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/custom/CustomZonedDateTime.java [hunk 2]
```diff
@@ -0,0 +1,193 @@
...
+import java.time.temporal.TemporalAmount;
+import java.time.temporal.TemporalField;
+import java.time.temporal.TemporalUnit;
+import java.util.Objects;
+
+/**
+ * This class is meant as sort-of <b>decorator</b> over <code>ZonedDateTime</code>, that is a final class.
+ * It is used to provide a string representation that preserves seconds even when they are zero,
+ */
+public final class CustomZonedDateTime
```
Comment (yesamer) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/custom/CustomZonedDateTime.java]: The name looks generic. What About `IsoZonedDateTime` ?
@AthiraHari77 @gitgabrio WDYT?

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/custom/CustomZonedDateTime.java [hunk 3]
```diff
@@ -0,0 +1,193 @@
...
+    public static CustomZonedDateTime of(LocalDate date, LocalTime time, ZoneId zone) {
+        return new CustomZonedDateTime(ZonedDateTime.of(date, time, zone));
+    }
+
+    public static CustomZonedDateTime from(TemporalAccessor temporal) {
+        return new CustomZonedDateTime(ZonedDateTime.from(temporal));
+    }
+
+    public static CustomZonedDateTime of(int coercedYear, int coercedMonth, int coercedDay, int coercedHour, int coercedMinute, int coercedSecond, int i, ZoneId zoneId) {
+        return new CustomZonedDateTime(ZonedDateTime.of(coercedYear, coercedMonth, coercedDay, coercedHour, coercedMinute, coercedSecond, i, zoneId));
```
[the remark this answers is not in the document]
Comment (yesamer) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/custom/CustomZonedDateTime.java]: @AthiraHari77 if the original class manages that as `i`, please ignore this. I think we should keep 1:1 copy where the behavior doesn't change.

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/custom/FormattedZonedDateTime.java [hunk 4]
```diff
@@ -0,0 +1,193 @@
...
+    public boolean equals(Object o) {
+        if (this == o) {
+            return true;
+        }
+        if (o instanceof CustomZonedDateTime that) {
+            return Objects.equals(zonedDateTime, that.zonedDateTime);
+        }
+        if (o instanceof ZonedDateTime other) {
+            return Objects.equals(zonedDateTime, other);
+        }
```
[the remark this answers is not in the document]
Comment (yesamer) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/custom/FormattedZonedDateTime.java:194]: @AthiraHari77 The original class manages that in this way:    

```
public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        return obj instanceof ZonedDateTime other
                && dateTime.equals(other.dateTime)
                && offset.equals(other.offset)
                && zone.equals(other.zone);
    }
```
About ZonedDateTime vs CustomZonedDateTime: is a realistic scenario that those 2 types are compared?

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/custom/CustomZonedDateTime.java (hunk 2 above)
Comment (gitgabrio) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/custom/CustomZonedDateTime.java]: TBH not sure to follow: why it should be "Iso" ?
This class is exactly a "Custom" version of the (wrapped) ZonedDateTime to "override" the toString method 🤔

Comment (yesamer) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/custom/CustomZonedDateTime.java]: @gitgabrio Yeah, maybe ISO is wrong, but Custom is too generic in my opinion. Why is custom?
`FormattedZonedDateTime`?

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/custom/FormattedZonedDateTime.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (gitgabrio) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/custom/FormattedZonedDateTime.java:194]: @yesamer the reason for the CustomZonedDateTime is to simply override the to string method - under all the other aspects it should be considered exactly the same - hence the check only on the wrapped instance.
Anyway, being different classes, it is hard to imagine a generic collection that contains both

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/DateAndTimeFunction.java [hunk 5]
```diff
@@ -136,7 +136,7 @@ public FEELFnResult<TemporalAccessor> invoke(@ParameterName( "from" ) String val
 
         try {
             if( val.contains( "T" ) ) {
-                return FEELFnResult.ofResult(FEEL_DATE_TIME.parseBest(val, ZonedDateTime::from, OffsetDateTime::from, LocalDateTime::from));
+                return FEELFnResult.ofResult(FEEL_DATE_TIME.parseBest(val, CustomZonedDateTime::from, OffsetDateTime::from, LocalDateTime::from));
             } else {
                 LocalDate value = DateTimeFormatter.ISO_DATE.parse(val, LocalDate::from);
                 return FEELFnResult.ofResult( LocalDateTime.of(value, LocalTime.of(0, 0)));
```
[the remark this answers is not in the document]
Comment (gitgabrio) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/DateAndTimeFunction.java]: @AthiraHari77 could you please verify that ?

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/CodegenUtils.java [hunk 6]
```diff
@@ -151,22 +153,10 @@ public static VariableDeclarationExpr getObjectExpression(Object object, String
         } else if (object instanceof String string) {
             return getVariableDeclaratorWithInitializerExpression(variableName, STRING_CT,
                                                                   new StringLiteralExpr(escapeJava(string)));
+        } else if (object instanceof CustomZonedDateTime customZonedDateTime) {
+            return getVariableDeclaratorWithZonedDateTime(variableName, customZonedDateTime.getZonedDateTime());
```
[the remark this answers is not in the document]
Comment (gitgabrio) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/CodegenUtils.java]: @AthiraHari77 why this change ?

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/DateTimeEvalHelper.java [hunk 7]
```diff
@@ -56,6 +57,8 @@ public static long valuedt(TemporalAccessor datetime, ZoneId otherTimezoneOffset
             return ((ZonedDateTime) datetime).toEpochSecond();
         } else if (datetime instanceof OffsetDateTime) {
             return ((OffsetDateTime) datetime).toEpochSecond();
+        } else if (datetime instanceof CustomZonedDateTime) {
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/DateTimeEvalHelper.java]: @AthiraHari77 could you please use the new java construct -> 

```
else if (datetime instanceof CustomZonedDateTime customZonedDateTime) {
return customZonedDateTime.getZonedDateTime().toEpochSecond();
```
(it avoid the cast and simplify a bit the code)

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/EvalHelper.java [hunk 8]
```diff
@@ -190,6 +191,8 @@ public static PropertyValueResult getDefinedValue(final Object current, final St
                         result = BigDecimal.valueOf(dtAtMidnightUTC.toEpochSecond());
                     } else if (current instanceof ZonedDateTime) {
                         result = BigDecimal.valueOf(((ZonedDateTime) current).toEpochSecond());
+                    } else if (current instanceof CustomZonedDateTime) {
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/EvalHelper.java]: @AthiraHari77 same as previous comment

**Review by gitgabrio — COMMENTED** [review]
Some doubts/comments on my side

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/CodegenUtils.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (AthiraHari77) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/CodegenUtils.java]: @gitgabrio  **CustomZonedDateTime** falls through to the generic TemporalAccessor handler which uses **toParsableString()** to re-parse it. But the toParsableString() method is stripping out the date part. The issue is that toParsableString() is optimal only for time values, not date-time values. Due to this few scenarios like below fails.
**"date and time(\"2018-12-08T00:00:00\") = date and time(\"2018-12-08T00:00:00@Europe/Rome\")"**

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/CodegenUtils.java [hunk 9]
```diff
@@ -181,6 +171,22 @@ public static VariableDeclarationExpr getObjectExpression(Object object, String
         }
     }
 
+    private static VariableDeclarationExpr getVariableDeclaratorWithZonedDateTime(String variableName, ZonedDateTime zonedDateTime) {
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/CodegenUtils.java]: Great idea to create this common method. Maybe a unit test ?

**Review by gitgabrio — COMMENTED** [review]
HI @AthiraHari77 , thanks for the good work.
Anyway, I could not find a test that verify the new toString behavior, i.e.

given a zoned date time at 0 minutes - 0 seconds, the returned string should not be truncated.
Am I missing something ?

**Comment by AthiraHari77** [comment]
> HI @AthiraHari77 , thanks for the good work. Anyway, I could not find a test that verify the new toString behavior, i.e.
> 
> given a zoned date time at 0 minutes - 0 seconds, the returned string should not be truncated. Am I missing something ?

@gitgabrio I have updated tests in class FormattedZonedDateTimeTest.java.

**Review by gitgabrio — APPROVED** [review]
Thanks, @AthiraHari77!  👍

**Review by yesamer — APPROVED** [review]
