### PR TITLE
[incubator-kie-issues#1882] DMN: Return full path of invalid element (until its root) from jit-executor

### LINKED ISSUE #1882: DMN: Return full path of invalid element (until its root) from jit-executor
[Untitled.79.dmn.txt](https://github.com/user-attachments/files/19337877/Untitled.79.dmn.txt)

Currently, DMN validation reports a message indicating the identifier of an invalid element, but not its container(s).

E.g.

```json
  [
    {
        "decisionId": "_A40F3AA4-2832-4D98-83F0-7D604F9A090F",
        "decisionName": "s",
        "result": null,
        "messages": [],
        "evaluationHitIds": {},
        "evaluationStatus": "FAILED"
    },
    {
        "decisionId": "_3DC41DB9-BE1D-4289-A639-24AB57ED082D",
        "decisionName": "New Decision",
        "result": null,
        "messages": [
            {
                "severity": "WARN",
                "message": "Missing expression for Decision Node 'New Decision'",
                "messageType": "MISSING_EXPRESSION",
                "sourceId": "_3DC41DB9-BE1D-4289-A639-24AB57ED082D",
                "path": "Untitled (79).dmn",
                "level": "WARNING"
            }
        ],
        "evaluationHitIds": {},
        "evaluationStatus": "SKIPPED"
    }
]
```

Scope of this ticket is to extend the message sent back by jit-executor to contain an ordered list with the full path (i.e. from root element to wrong one) of invalid element.
The first element of the list will be the root container, and the last will be the invalid element

Expected return

```json
  [
    {
        "decisionId": "_A40F3AA4-2832-4D98-83F0-7D604F9A090F",
        "decisionName": "s",
        "result": null,
        "messages": [],
        "evaluationHitIds": {},
        "evaluationStatus": "FAILED"
    },
    {
        "decisionId": "_3DC41DB9-BE1D-4289-A639-24AB57ED082D",
        "decisionName": "New Decision",
        "result": null,
        "messages": [
            {
                "severity": "WARN",
                "message": "Missing expression for Decision Node 'New Decision'",
                "messageType": "MISSING_EXPRESSION",
                "sourceId": "_3DC41DB9-BE1D-4289-A639-24AB57ED082D",
                "path": "Untitled (79).dmn",
                "level": "WARNING"
            }
        ],
        "evaluationHitIds": {},
        "evaluationStatus": "SKIPPED"
    },
    {
     "validationErrorPaths": [
       ["_3DC41DB9-BE1D-4289-A639-24AB57ED082D", "(intermediate_ids)", "_3DC41DB9-BE1D-4289-A639-24AB57ED082D"]
     ]
  }
]
```

### LINKED ISSUE #1907: DMN: investigate and eventually fix decision result when referring an invalid BKM
When a decision refers/uses a BKM defined outside decision itself, the engine correctly identify the BKM element as invalid, generating an ERROR message, but then the decision itself is executed without any warning/message, returning SUCCEED status and a null result.

Investigate reason for it and eventually fix it
Check it change breaks TCKs, too.

The following model shows that ("Decision1")

[DMN-MultipleInvalidElements.txt](https://github.com/user-attachments/files/19563737/DMN-MultipleInvalidElements.txt)

### PR DESCRIPTION
**Pull request by AthiraHari77**
Fixes https://github.com/apache/incubator-kie-issues/issues/1882
Fixes https://github.com/apache/incubator-kie-issues/issues/1907
Used by PR : https://github.com/apache/incubator-kie-kogito-apps/pull/2206

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

### CODE REVIEW

**Review by yesamer — APPROVED** [review]

File: kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNLiteralExpressionEvaluator.java [hunk 1]
```diff
@@ -86,21 +89,48 @@ public EvaluatorResult evaluate(DMNRuntimeEventManager dmrem, DMNResult dmnr) {
         EvaluationContextImpl ectx = feelInstance.newEvaluationContext(List.of(liListener), result.getContext().getAll());
         ectx.setDMNRuntime(dmrem.getRuntime());
         // in case an exception is thrown, the parent node will report it
+        // TODO: tricky workaround
```
Comment (jomarko) [inline kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNLiteralExpressionEvaluator.java]: Will be this TODO resolved as part of this PR or as part of a separate PR please?

Comment (AthiraHari77) [reply kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNLiteralExpressionEvaluator.java]: It is resolved in this PR, will remove the comments and have a clean up done.

Comment (jomarko) [reply kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNLiteralExpressionEvaluator.java]: @AthiraHari77 thank you

**Review by jomarko — APPROVED** [review]
Thank you for the PR!

**Review by baldimir — APPROVED** [review]
