### PR TITLE
[incubator-kie-issues#2064] Fixing usage of duplicated Input Data nodes with inherited decisions

### LINKED ISSUE #2064: Decision Engine: Decision Services doesn't work with Duplicate Input Nodes with the Same Name Across Models
It appears possible to have two input nodes with the same name but from different models when using the default namespace. For example: 

* dmn-a:
       a input → a decision
* dmn-a2 (includes dmn-a via default namespace):
       a input → a decision2
       a decision → a decision2
Although this setup is unusual, it’s technically allowed due to the use of default namespace imports. However, the engine currently returns the following error:

`REQ_NOT_FOUND: Required input '_0D2BA05B-1392-455A-865B-F02BAC981EB9' not found on node 'a decision'`

This message is misleading, as it suggests the setup is valid but fails due to a missing input. If having two input data nodes with the same name (but different IDs) is supported, what exactly does the engine expect in this case? If it’s not supported, then the error message should be improved to clearly indicate that this configuration is invalid.Example of request:
 
```
curl -X POST http://localhost:21345/jitdmn/dmnresult \ -H "Content-Type: application/json" \ -d '{ "context":

{ "a input": 21 }
, "mainURI": "dmn-a2.dmn", "resources": [ { "content": "dmn-a2 content", "URI": "dmn-a2.dmn" }, { "content": "dmn-a content", "URI": "dmn-a.dmn"} ]
```
[two-input-data-same-name (1).zip](https://jsw.ibm.com/secure/attachment/10766709/10766709_two-input-data-same-name+%281%29.zip)

### PR DESCRIPTION
**Pull request by gitgabrio**
Fixes https://github.com/apache/incubator-kie-issues/issues/2064

This PR:

1. add InputData from imported models inside importing ones, as per Decisions
2. create ad-hoc models and tests
3. improve message in case of missing inputdata at compile time

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

### CODE REVIEW

File: kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/UnnamedImportUtils.java [hunk 1]
```diff
@@ -45,31 +45,32 @@ public static boolean isInUnnamedImport(DMNNode node, DMNModelImpl model) {
...
 
-        mergedModel.getTypeRegistry().getTypes().forEach((s, stringDMNTypeMap) ->
+        importedModel.getTypeRegistry().getTypes().forEach((s, stringDMNTypeMap) ->
                                                                  stringDMNTypeMap.values().
-                                                                         forEach(dmnType -> parentModel.getTypeRegistry().registerType(dmnType)));
-        mergedModel.getDecisions().forEach(parentModel::addDecision);
-        mergedModel.getImportAliasesForNS().forEach((s, qName) -> parentModel.setImportAliasForNS(s, qName.getNamespaceURI(), qName.getLocalPart()));
+                                                                         forEach(dmnType -> importingModel.getTypeRegistry().registerType(dmnType)));
+        importedModel.getDecisions().forEach(importingModel::addDecision);
+        importedModel.getInputs().forEach(importingModel::addInput);
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/UnnamedImportUtils.java:60]: NOTICE

**Review by yesamer — APPROVED** [review]

**Review by baldimir — APPROVED** [review]
