### PR TITLE
[incubator-kie-issues#1771] Fixing BooleanEvalHelper to avoid class cast exceptions

### LINKED ISSUE #1771: Type cast error when a FEEL expression with mixed types are executed
The TCK Tests detected 4 new test failures that were not present the previous week:

- 0064-feel-conjunction 
-- [008_b](https://github.com/dmn-tck/tck/blob/5a40dc510f9cf9788fbc04cb4a79eb9a7c235e10/TestCases/compliance-level-3/0064-feel-conjunction/0064-feel-conjunction.dmn#L130)
-- [008_c](https://github.com/dmn-tck/tck/blob/5a40dc510f9cf9788fbc04cb4a79eb9a7c235e10/TestCases/compliance-level-3/0064-feel-conjunction/0064-feel-conjunction.dmn#L139)
- 0065-feel-disjunction 
-- [007_b](https://github.com/dmn-tck/tck/blob/5a40dc510f9cf9788fbc04cb4a79eb9a7c235e10/TestCases/compliance-level-3/0065-feel-disjunction/0065-feel-disjunction.dmn#L103)
-- [007_c](https://github.com/dmn-tck/tck/blob/5a40dc510f9cf9788fbc04cb4a79eb9a7c235e10/TestCases/compliance-level-3/0065-feel-disjunction/0065-feel-disjunction.dmn#L112)

This is the error
```
Message [id=0, level=ERROR, path=null, line=139, column=-1
   text=DMN: Error evaluating Decision node 'decision008_c': class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap') (DMN id: _decision008_c, Error evaluating node) ]
```
and this is one of the involved Decision Node:
```
<decision name="decision008_c" id="_decision008_c">
    <description>Tests FEEL expression: '"true" or false' and expects result: 'null (boolean)'</description>
    <question>Result of FEEL expression '"true" or false'?</question>
    <allowedAnswers>null (boolean)</allowedAnswers>
    <variable typeRef="boolean" name="decision008_c"/>
    <literalExpression>
        <text>"true" or false</text>
    </literalExpression>
</decision>
```

### PR DESCRIPTION
**Pull request by gitgabrio**
Fixes https://github.com/apache/incubator-kie-issues/issues/1771

This PR:
1. refactor BooleanEvalHelper methods to avoid class cast exception
2. add related TCK cases to FEELTernaryLogicTest
3. add unit tests for modified methods

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

### CODE REVIEW

File: kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/FEELTernaryLogicTest.java [hunk 1]
```diff
@@ -1,4 +1,4 @@
-/**
+/*
```
Comment (yesamer) [inline kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/FEELTernaryLogicTest.java:1]: @gitgabrio Ooops

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/BooleanEvalHelper.java [hunk 2]
```diff
@@ -1,4 +1,4 @@
-/**
+/*
```
Comment (yesamer) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/BooleanEvalHelper.java:1]: @gitgabrio Oops

**Review by yesamer — APPROVED** [review]

File: kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/FEELTernaryLogicTest.java (hunk 1 above)
Comment (gitgabrio) [reply kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/FEELTernaryLogicTest.java:1]: @yesamer 
This is wanted.
License header should not be "javadoc", but comment

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/BooleanEvalHelper.java (hunk 2 above)
Comment (gitgabrio) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/BooleanEvalHelper.java:1]: @yesamer 
This is wanted.
License header should not be "javadoc", but comment

**Review by baldimir — APPROVED** [review]
