### PR TITLE
[incubator-kie-drools-5847] Flaky KieContainerTest.testIncrementalCom…

### LINKED ISSUE #5847: Flaky KieContainerTest.testIncrementalCompilationSynchronization timeout
KieContainerTest.testIncrementalCompilationSynchronization very rarely hits 20 sec timeout.
```
[2022-03-03T16:20:06.546Z] [ERROR] Tests run: 10, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 20.29 s <<< FAILURE! - in org.drools.mvel.integrationtests.KieContainerTest
[2022-03-03T16:20:06.546Z] [ERROR] testIncrementalCompilationSynchronization[KieBase type=CLOUD_IDENTITY](org.drools.mvel.integrationtests.KieContainerTest)  Time elapsed: 20.022 s  <<< ERROR!
[2022-03-03T16:20:06.546Z] org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.phreak.AddRemoveRule.findPathToFlush(AddRemoveRule.java:647)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.reteoo.LeftInputAdapterNode.doInsertSegmentMemory(LeftInputAdapterNode.java:255)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.reteoo.LeftInputAdapterNode.doInsertObject(LeftInputAdapterNode.java:232)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.reteoo.LeftInputAdapterNode.assertObject(LeftInputAdapterNode.java:176)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.reteoo.SingleObjectSinkAdapter.propagateAssertObject(SingleObjectSinkAdapter.java:70)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.reteoo.ObjectTypeNode.propagateAssert(ObjectTypeNode.java:297)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.reteoo.ObjectTypeNode.assertInitialFact(ObjectTypeNode.java:265)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.impl.StatefulKnowledgeSessionImpl.initInitialFact(StatefulKnowledgeSessionImpl.java:756)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.impl.StatefulKnowledgeSessionImpl.initInitialFact(StatefulKnowledgeSessionImpl.java:744)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.impl.StatefulKnowledgeSessionImpl.bindRuleBase(StatefulKnowledgeSessionImpl.java:406)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.impl.StatefulKnowledgeSessionImpl.<init>(StatefulKnowledgeSessionImpl.java:332)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.impl.StatefulKnowledgeSessionImpl.<init>(StatefulKnowledgeSessionImpl.java:278)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.common.PhreakWorkingMemoryFactory.createWorkingMemory(PhreakWorkingMemoryFactory.java:35)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.impl.KnowledgeBaseImpl.internalCreateStatefulKnowledgeSession(KnowledgeBaseImpl.java:381)
[2022-03-03T16:20:06.546Z]      at app//org.drools.core.impl.KnowledgeBaseImpl.newKieSession(KnowledgeBaseImpl.java:365)
[2022-03-03T16:20:06.547Z]      at app//org.drools.core.impl.KnowledgeBaseImpl.newKieSession(KnowledgeBaseImpl.java:344)
[2022-03-03T16:20:06.547Z]      at app//org.drools.compiler.kie.builder.impl.KieContainerImpl.newKieSession(KieContainerImpl.java:599)
[2022-03-03T16:20:06.547Z]      at app//org.drools.compiler.kie.builder.impl.KieContainerImpl.newKieSession(KieContainerImpl.java:519)
[2022-03-03T16:20:06.547Z]      at app//org.drools.compiler.kie.builder.impl.KieContainerImpl.newKieSession(KieContainerImpl.java:502)
[2022-03-03T16:20:06.547Z]      at app//org.drools.mvel.integrationtests.KieContainerTest.testIncrementalCompilationSynchronization(KieContainerTest.java:279)
[2022-03-03T16:20:06.547Z]      at java.base@11.0.14.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-03-03T16:20:06.547Z]      at java.base@11.0.14.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-03-03T16:20:06.547Z]      at java.base@11.0.14.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-03-03T16:20:06.547Z]      at java.base@11.0.14.1/java.lang.reflect.Method.invoke(Method.java:566)
[2022-03-03T16:20:06.547Z]      at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
[2022-03-03T16:20:06.547Z]      at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[2022-03-03T16:20:06.547Z]      at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
[2022-03-03T16:20:06.547Z]      at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[2022-03-03T16:20:06.547Z]      at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
[2022-03-03T16:20:06.547Z]      at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
[2022-03-03T16:20:06.547Z]      at java.base@11.0.14.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2022-03-03T16:20:06.547Z]      at java.base@11.0.14.1/java.lang.Thread.run(Thread.java:829)

```

### PR DESCRIPTION
**Pull request by tkobayas**
…pilationSynchronization timeout

**Issue**: 

* https://github.com/apache/incubator-kie-drools/issues/5847

### CODE REVIEW

File: drools-test-coverage/test-compiler-integration/src/test/java/org/drools/mvel/integrationtests/KieContainerTest.java [hunk 1]
```diff
@@ -267,6 +270,13 @@ public void testIncrementalCompilationSynchronization() {
 
         Thread t = new Thread(() -> {
             for (int i = 1; i < 10; i++) {
+                while (!previousRuleExists(kieContainer, i)) { // if rule1 exists, we can change it to rule2
+                    try {
+                        Thread.sleep(1);
+                    } catch (InterruptedException e) {
+                        throw new RuntimeException(e);
+                    }
+                }
```
Comment (tkobayas) [inline drools-test-coverage/test-compiler-integration/src/test/java/org/drools/mvel/integrationtests/KieContainerTest.java:279]: See the analysis: https://github.com/apache/incubator-kie-drools/pull/5848#issuecomment-2191045509

The kbase update modification will be done by its own thread immediately **or** by main thread polling `kbaseModificationsQueue` later.
https://github.com/apache/incubator-kie-drools/blob/main/drools-kiesession/src/main/java/org/drools/kiesession/rulebase/SessionsAwareKnowledgeBase.java#L287-L297
```java
    public void enqueueModification(Runnable modification) {
        if ( tryLockAndDeactivate() ) {
            try {
                modification.run();
            } finally {
                unlockAndActivate();
            }
        } else {
            kbaseModificationsQueue.offer(modification);
        }
    }
```

So we cannot assume that the update modifications will be done in the expected order. In the failure case, `remove rule1, add rule2` was executed before `remove rule0, add rule1`, so there was no chance to remove rule1.

I think it's not an engine bug, but we should fix the test case. With the PR fix, we make sure that we call `updateToVersion` only when the previous rule exists.

The test case can still test the multi-thread concurrency of `fireAllRules` and `updateToVersion`. Is it fine for the test purpose? @mariofusco 

---
Btw, this PR `while` and `Thread.sleep` logic is a naive approach and can be re-written by `ScheduledExecutorService`, but I think this one is concise and easier to understand.

**Comment by tkobayas** [comment]
@mariofusco @lucamolteni @pibizza , please review. Thanks!

File: drools-test-coverage/test-compiler-integration/src/test/java/org/drools/mvel/integrationtests/KieContainerTest.java (hunk 1 above)
Comment (mariofusco) [reply drools-test-coverage/test-compiler-integration/src/test/java/org/drools/mvel/integrationtests/KieContainerTest.java:279]: @tkobayas Great work in analyzing this issue and yes I agree that the problem is in how the test is written and its wrong assumption on the strict execution order and not in the actual code.

**Review by mariofusco — APPROVED** [review]

**Review by lucamolteni — APPROVED** [review]
