### PR TITLE
[kie-issues#1930] replace() and matches() functions doesn't work with XML Character References

### LINKED ISSUE #1930: replace() and matches() functions doesn't work with XML Character References
XML Character References are special characters internally used in XML to refer to other entities Objects.
Those characters are:
- `&`
- `"`
- `'`
- `<`
- `>`

DMN Functions like `matches()` and `replace()` work with XPath specs and implementation. Passing a string that contains one or more of the above characters list will throw an exception. 
To fix the issue, it's necessary to escape the above character list, replacing them with:
- `&`  ---> `&amp;`
- `"`    ---> `&quot;`
- `'`    ---> `&apos;`
- `<`   ---> `&lt;`
- `>`   ---> `&gt;`

### PR DESCRIPTION
**Pull request by yesamer**
Closes https://github.com/apache/incubator-kie-issues/issues/1930

XML Character References are special characters internally used in XML to refer to other entities Objects.
Those characters are:
- `&`
- `"`
- `'`
- `<`
- `>`

DMN Functions like `matches()` and `replace()` work with XPath specs and implementation. Passing a string that contains one or more of the above characters list will throw an exception. 
To fix the issue, it's necessary to escape the above character list, replacing them with:
- `&`  ---> `&amp;`
- `"`    ---> `&quot;`
- `'`    ---> `&apos;`
- `<`   ---> `&lt;`
- `>`   ---> `&gt;`

### CODE REVIEW

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/XQueryImplUtil.java [hunk 1]
```diff
@@ -26,17 +26,25 @@
 import net.sf.saxon.s9api.XQueryExecutable;
 import net.sf.saxon.s9api.SaxonApiException;
 
+import java.util.regex.Pattern;
+
 public class XQueryImplUtil {
 
+    static Pattern XML_CHARACTER_REFERENCES_PATTERN = Pattern.compile("['\"&<>]");
```
Comment (bncriju) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/XQueryImplUtil.java]: Could be private static final since it's not accessed externally and is constant.

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/XQueryImplUtil.java [hunk 2]
```diff
@@ -26,17 +26,25 @@
...
+
+    private XQueryImplUtil() {
+        // Util class with static methods only.
+    }
+
     public static Boolean executeMatchesFunction(String input, String pattern, String flags) {
         flags = flags == null ? "" : flags;
-        String xQueryExpression = String.format("matches('%s', '%s', '%s')", input, pattern, flags);
+        String xQueryExpression = String.format("matches('%s', '%s', '%s')", sanitizeXmlCharacterReferences(input), sanitizeXmlCharacterReferences(pattern), flags);
```
Comment (bncriju) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/XQueryImplUtil.java]: renaming method 'sanitizeXmlCharacterReferences' to precise method name 'escapeXmlSpecialCharactersForXQuery' would help

File: kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/functions/ReplaceFunctionTest.java [hunk 3]
```diff
@@ -98,6 +98,20 @@ private static Object[][] invokeWithoutFlagsPatternTestData() {
...
+    }
+
+    private static Object[][] invokeWithXmlCharacterReferencesData() {
+        return new Object[][] {
+                { "abc&123", "abc", "123", "123&123" },
+                { "abc'123", "abc'", "123", "123123" },
+                { "abc\"123", "abc\"", "123<>", "123<>123" }
+        };
+    }
+
```
Comment (bncriju) [inline kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/functions/ReplaceFunctionTest.java:115]: Adding a test that verifies the raw XQuery expression string would be fine, to ensure the escaping looks exactly as expected in the generated string eg: '<&>' as input and pattern with no flag mentioned.

**Review by bncriju — COMMENTED** [review]
Code looks fine for me. Few minor suggestions provided. Thanks @yesamer for the PR

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/XQueryImplUtil.java (hunk 2 above)
Comment (yesamer) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/XQueryImplUtil.java]: @bncriju Changed to `escapeXmlCharactersReferencesForXPath` thank you.

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/XQueryImplUtil.java (hunk 1 above)
Comment (yesamer) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/XQueryImplUtil.java]: Done

File: kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/functions/ReplaceFunctionTest.java (hunk 3 above)
Comment (yesamer) [reply kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/functions/ReplaceFunctionTest.java:115]: Done

**Review by bncriju — APPROVED** [review]

**Review by baldimir — APPROVED** [review]
