### PR TITLE
[kie-issues#1923] includes in kmodule.xml doesn't work for Quarkus and Spring Boot projects

### LINKED ISSUE #1923: includes in kmodule.xml doesn't work for Quarkus and Spring Boot projects
When having a Quarkus or Spring Boot business service with rules and a kmodule.xml file defined as this: 

```
<?xml version="1.0" encoding="UTF-8"?>
<kmodule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.drools.org/xsd/kmodule">
<kbase name="IncludedKieBase" packages="org.kie.kogito.rules.otherpackage" />
<kbase name="SomeKieBase" packages="org.kie.kogito.rules.embedded" includes="IncludedKieBase" />
</kmodule>
```

when firing rules from KieBase with name SomeKieBase, the rules from IncludedKieBase are not fired. 

I have a fix, will submit the PR soon.

### PR DESCRIPTION
**Pull request by baldimir**
Fixes https://github.com/apache/incubator-kie-issues/issues/1923

This PR fixes code generation of Project classes (ProjectModel, ProjectRuntime) and fixes KieBaseBuilder, to include rules from KieBases defined in the "includes", e.g. in kmodule.xml. See the [issue](https://github.com/apache/incubator-kie-issues/issues/1923) for details. 

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

### CODE REVIEW

**Review by yesamer — APPROVED** [review]
Thank you @baldimir

File: drools-model/drools-model-codegen/src/main/java/org/drools/model/codegen/project/KieSessionModelBuilder.java [hunk 1]
```diff
@@ -73,14 +73,23 @@ private Map<String, List<String>> getModelByKBase(Collection<CodegenPackageSourc
...
+                for (String includedKieBaseName : entry.getValue().getIncludes()) {
+                    modelsForKieBase.addAll(getModelsForKieBaseWithoutIncludes(kieBaseModels.get(includedKieBaseName), modelsByPackage));
+                }
+            }
+            modelsByKBase.put(entry.getKey(), modelsForKieBase);
         }
         return modelsByKBase;
     }
 
+    private List<String> getModelsForKieBaseWithoutIncludes(final KieBaseModel kieBaseModel, final Map<String, String> modelsByPackage) {
```
Comment (gitgabrio) [inline drools-model/drools-model-codegen/src/main/java/org/drools/model/codegen/project/KieSessionModelBuilder.java:124]: Hi @baldimir 
could you please add a javadoc explaining the logic of this method ?
Moreover, it should be tested, which `private` does not allow

File: drools-model/drools-model-codegen/src/main/java/org/drools/model/codegen/project/KieSessionModelBuilder.java [hunk 2]
```diff
@@ -73,14 +73,23 @@ private Map<String, List<String>> getModelByKBase(Collection<CodegenPackageSourc
         Map<String, String> modelsByPackage = getModelsByPackage(packageSources);
         Map<String, List<String>> modelsByKBase = new HashMap<>();
         for (Map.Entry<String, KieBaseModel> entry : kieBaseModels.entrySet()) {
-            List<String> kieBasePackages = entry.getValue().getPackages();
-            boolean isAllPackages = kieBasePackages.isEmpty() || (kieBasePackages.size() == 1 && kieBasePackages.get(0).equals("*"));
-            modelsByKBase.put(entry.getKey(),
-                    isAllPackages ? new ArrayList<>(modelsByPackage.values()) : kieBasePackages.stream().map(modelsByPackage::get).filter(Objects::nonNull).collect(toList()));
+            List<String> modelsForKieBase = getModelsForKieBaseWithoutIncludes(entry.getValue(), modelsByPackage);
```
Comment (gitgabrio) [inline drools-model/drools-model-codegen/src/main/java/org/drools/model/codegen/project/KieSessionModelBuilder.java]: Hi @baldimir 
I have the impression that a sort of recursion would be needed, i.e. if the "includes" contains `includes`, in turns, I have the impression it is not managed here

File: drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/KieBaseBuilderTest.java [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.drools.model.DSL.declarationOf;
+import static org.drools.model.DSL.on;
+import static org.drools.model.PatternDSL.pattern;
+import static org.drools.model.PatternDSL.rule;
+
+public class KieBaseBuilderTest {
+
+    @Test
+    public void createKieBaseFromModelWithKieBaseIncludes() {
```
Comment (gitgabrio) [inline drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/KieBaseBuilderTest.java]: Hi @baldimir 
Could you please add a test with "nested" includes ? Thanks!

**Review by gitgabrio — CHANGES_REQUESTED** [review]

File: drools-model/drools-model-codegen/src/main/java/org/drools/model/codegen/project/KieSessionModelBuilder.java (hunk 1 above)
Comment (baldimir) [reply drools-model/drools-model-codegen/src/main/java/org/drools/model/codegen/project/KieSessionModelBuilder.java:124]: The method was already there and it is very hard to test as it is part of codegen. I think if examples work, it will test that it works. I know it is not ideal, however I want to avoid adding another complex testing into this. I could do it as part of separate ticket. What do you think, please?

File: drools-model/drools-model-codegen/src/main/java/org/drools/model/codegen/project/KieSessionModelBuilder.java (hunk 2 above)
Comment (baldimir) [reply drools-model/drools-model-codegen/src/main/java/org/drools/model/codegen/project/KieSessionModelBuilder.java]: Yes, that is true. I will take a look.

Comment (baldimir) [reply drools-model/drools-model-codegen/src/main/java/org/drools/model/codegen/project/KieSessionModelBuilder.java]: Should be fixed.

File: drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/KieBaseBuilderTest.java (hunk 3 above)
Comment (baldimir) [reply drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/KieBaseBuilderTest.java]: I extended the existing test.

File: drools-model/drools-model-codegen/src/main/java/org/drools/model/codegen/project/KieSessionModelBuilder.java (hunk 1 above)
Comment (gitgabrio) [reply drools-model/drools-model-codegen/src/main/java/org/drools/model/codegen/project/KieSessionModelBuilder.java:124]: Ok. I was hoping that it would be a good time to try to improve that part a bit, anyway I see the point.

**Review by mariofusco — APPROVED** [review]

File: drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/KieBaseBuilderTest.java [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+        final KieBaseModel kieBaseModelIncluded = kieModuleModel.newKieBaseModel("IncludedModel");
+        kieBaseModelIncluded.addPackage("org.drools.test.included");
+        kieBaseModelIncluded.addInclude("IncludedInIncluded");
+
+        final KieBaseModel kieBaseModelThatIncludes = kieModuleModel.newKieBaseModel("ModelThatIncludesTheOther");
+        kieBaseModelThatIncludes.addPackage("org.drools.test.main");
+        kieBaseModelThatIncludes.addInclude("IncludedModel");
+
+        final KieBase kieBase = KieBaseBuilder.createKieBaseFromModel(List.of(model1, model2, model3), kieBaseModelThatIncludes, kieModuleModel);
+        try (KieSession ksession = kieBase.newKieSession()) {
```
Comment (gitgabrio) [inline drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/KieBaseBuilderTest.java:79]: HI @baldimir 
Since it is not possible to unit-test the private methods created/modified elsewhere, could you please insert some assert to verify - somehow - that the kieBase/kiesession actually contains the data from the included models ?
I see that is is implicitily verified by `isEqualTo(3)` , but it is a very indirect assertion and depends on too many other conditions

Comment (baldimir) [reply drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/KieBaseBuilderTest.java:79]: I commented the assert, so it should be more clear what it checks. Is that fine, please?

Comment (baldimir) [reply drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/KieBaseBuilderTest.java:79]: As discussed offline last week, merging this. The test will be too complex.
