### PR TITLE
[KIE-1077] fix executable model generation with generics

### LINKED ISSUE #1077: Executable model cannot process a class with a generic field
The following reproducer 

```
    public static class ClassWithGenericField<P extends Address> {

        private P extendedAddress;

        public ClassWithGenericField(final P extendedAddress) {
            this.extendedAddress = extendedAddress;
        }

        public P getExtendedAddress() {
            return extendedAddress;
        }

        public void setExtendedAddress(final P extendedAddress) {
            this.extendedAddress = extendedAddress;
        }
    }

    @Test
    public void testClassWithGenericField() {
        String str =
                "import " + ClassWithGenericField.class.getCanonicalName() + ";\n " +
                "import " + List.class.getCanonicalName() + ";\n " +
                "global List results;\n " +
                "rule R when\n " +
                "    ClassWithGenericField($addressStreet: extendedAddress.street) \n " +
                "then\n " +
                "    results.add($addressStreet);\n " +
                "end";

        KieSession ksession = getKieSession(str);
        List<String> results = new ArrayList<>();
        ksession.setGlobal("results", results);

        final Address address = new Address("someStreet", 1, "Levice");
        final ClassWithGenericField<Address> classWithGenericField = new ClassWithGenericField<>(address);

        ksession.insert(classWithGenericField);
        assertThat(ksession.fireAllRules()).isEqualTo(1);
    }
```

works with interpreted drl, but fails the generation of the executable model 

```
15:14:21.111 [main] ERROR o.d.c.k.b.impl.AbstractKieProject.buildKnowledgePackages:280 - Unable to build KieBaseModel:defaultKieBase
InvalidExpressionErrorResult: Unknown field street on P
```

### PR DESCRIPTION
**Pull request by mariofusco**
Fixes https://github.com/apache/incubator-kie-issues/issues/1077

### CODE REVIEW

File: drools-util/src/main/java/org/drools/util/ClassUtils.java [hunk 1]
```diff
@@ -597,11 +595,11 @@ public static Class<?> toRawClass(Type type) {
...
             return ( Class ) type;
         }
-        if (type instanceof ParameterizedType ) {
+        if (type instanceof ParameterizedType) {
             return toRawClass( (( ParameterizedType ) type).getRawType() );
         }
-        if (type instanceof TypeVariable ) {
-            return Object.class;
+        if (type instanceof TypeVariable typeVar) {
+            return typeVar.getBounds().length == 1 ? toRawClass(typeVar.getBounds()[0]) : Object.class;
```
Comment (mariofusco) [inline drools-util/src/main/java/org/drools/util/ClassUtils.java:602]: This one-liner is the only actual fix. All other changes are refactors that I made to improve the code readability (and clarify to myself what was happening) while investigating this issue.

File: drools-model/drools-model-codegen/src/test/java/org/drools/model/codegen/execmodel/GenericsTest.java [hunk 2]
```diff
@@ -40,20 +40,20 @@ public void testGenericsAccumulateInlineCode() {
...
-                "rule R when\n" +
-                "  $l : List() from accumulate (Person($addrList : addresses),\n" +
-                "         init( List<String> cityList = new ArrayList(); ),\n" +
-                "         action( for(Address addr: $addrList){String city = addr.getCity(); cityList.add(city);} ),\n" +
-                "         result( cityList )\n" +
-                "       )\n" +
-                "then\n" +
-                "  results.add($l);\n" +
-                "end";
+                        "import " + Address.class.getCanonicalName() + ";\n" +
```
Comment (lucamolteni) [inline drools-model/drools-model-codegen/src/test/java/org/drools/model/codegen/execmodel/GenericsTest.java:43]: Wrong formatting

**Review by lucamolteni — APPROVED** [review]
Are these indentation

**Review by baldimir — APPROVED** [review]
