### PR TITLE
[incubator-kie-issues#2083] Fix correct overrides of expressionLanguage

### LINKED ISSUE #2083: FEEL: expression-specific configuration does not take precedence during evaluation
The attached model [bfeel-global-feel-local.dmn](https://jsw.ibm.com/secure/attachment/10917188/10917188_bfeel-global-feel-local.dmn) is configured with two FEEL namespaces:

- On the global level, B-FEEL is used
- On the single expression level: FEEL is used

This expression that should be evaluated using FEEL is declared as:

`sum([Person.Age, "1", 4])`

_using FEEL, `null` should be returned_, however, expression is evaluated to non null value:

Image

[bfeel-global-feel-local.txt](https://github.com/user-attachments/files/22132211/bfeel-global-feel-local.txt)

### PR DESCRIPTION
**Pull request by gitgabrio**
Fixes https://github.com/apache/incubator-kie-issues/issues/2083

This PR:

1. fix the FEEL language setting on dynamically instantiated (nested) Context
2. add minor refactoring to inheritance tree to remove duplicated code
3. add unit test to cover the core modification
4. add integration tests on specially-crafted dmn to verify correct behavior under different scenarios

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

### CODE REVIEW

**Review by baldimir — APPROVED** [review]

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/DMNEvaluatorCompilerTest.java [hunk 1]
```diff
@@ -92,17 +119,26 @@ void getFEELDialectAdaptedFEELFEELURIExpressionLanguage() {
...
         String expressionLanguage = FEELDialect.BFEEL.getNamespace();
         LiteralExpression expression = getLiteralExpression(expressionLanguage);
-        FEEL retrieved = DMNEvaluatorCompiler.getFEELDialectAdaptedFEEL(DMN_COMPILER_CONTEXT, expression, expressionLanguage);
+        FEEL retrieved = DMNEvaluatorCompiler.getFEELDialectAdaptedFEEL(DEFAULT_DMN_COMPILER_CONTEXT, expression, expressionLanguage);
         assertThat(retrieved).isNotNull().isInstanceOf(FEELImpl.class);
         assertThat(((FEELImpl) retrieved).getFeelDialect()).isEqualTo(FEELDialect.BFEEL);
     }
 
+    @Test
+    void getFEELDialectAdaptedFEELSFEELExpressionLanguage() {
```
Comment (jomarko) [inline kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/DMNEvaluatorCompilerTest.java:128]: The method name is challenging to understand.

Is this test to check FEEL language set on expression level overrides FEEL language set on global level?

**Review by jomarko — COMMENTED** [review]
Thank you @gitgabrio . I have only feedback to the tests.

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/DMNEvaluatorCompilerTest.java (hunk 1 above)
Comment (gitgabrio) [reply kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/DMNEvaluatorCompilerTest.java:128]: both 
`getFEELDialectAdaptedFEELBFEELExpressionLanguage() `

and 

`getFEELDialectAdaptedFEELSFEELExpressionLanguage()`

verify the actual overrides of feel expression language.
The former check that the global (S)FEEL get overwritten with BFEEL, and the latter is the other way around, i.e. global B-FEEL overwritten with (S)FEEL.
This latter one is exactly the failing case behind this ticket.

The logic of naming is
method tested (`getFEELDialectAdaptedFEEL`) + some differentiating identifier
... yup, agree at first read is cumbersome

**Review by jomarko — APPROVED** [review]
