### PR TITLE
[incubator-kie-issues#2065] Decision Services doesn't work If the import name and the inputName is same

### LINKED ISSUE #2065: Decision Engine: Decision Services doesn't work If the import name and the inputName is same
Scenario: If the import name and the inputName is same then i am getting below error.

Request:

`"context": { "My Input": "1", "A": { "A": 1 } },`

Response:
{
"details": "Error id ee96cda2-4faa-4159-a98b-cbfd24101d03-5, org.jboss.resteasy.spi.UnhandledException: java.lang.StackOverflowError",
}.  

Attaching dmn here: please check MyDmn-0 in the below zip file.

[same-importname-inputname-issue.zip](https://github.com/user-attachments/files/21851245/same-importname-inputname-issue.zip)

### PR DESCRIPTION
**Pull request by gitgabrio**
Fixes https://github.com/apache/incubator-kie-issues/issues/2065

This PR implement a specific management of imported input data whose name clashes with the name of the import itself.

Critical modifications are inside 

1. DMNRuntimeUtils#processTopmostModelInputDataNode(DMNContext, String,
                                                 DMNModelImpl.ModelImportTuple, DMNModelImpl)
                                                 
2. DMNRuntimeUtils#processTopmostModelInputDataNodeWithClashingNames(DMNContext, String, DMNModelImpl.ModelImportTuple,  DMNModelImpl)
                                                 
Beside that, all the "static" methods have been moved from DMNRuntimeImpl to DMNRuntimUtils, adapting test class accordingly
                                                 

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

### CODE REVIEW

File: kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNRuntimeUtils.java [hunk 1]
```diff
@@ -0,0 +1,276 @@
...
+                                         DMNModelImpl model) {
+        DMNModelImpl topmostModel = topmostModelTuple.getModel();
+        for (InputDataNode topmostInput : topmostModel.getInputs()) {
+            processTopmostModelInputDataNode(context, topmostInput.getName(), topmostModelTuple, model);
+        }
+    }
+
+    static void processTopmostModelInputDataNode(DMNContext context, String topmostInputName,
+                                                 DMNModelImpl.ModelImportTuple topmostModelTuple, DMNModelImpl model) {
+        if (Objects.equals(topmostInputName, topmostModelTuple.getImportName())) {
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNRuntimeUtils.java:85]: Important change

File: kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNRuntimeUtils.java [hunk 2]
```diff
@@ -0,0 +1,276 @@
...
+            processTopmostModelInputDataNodeWithClashingNames(context, topmostInputName,
+                                                              topmostModelTuple, model);
+        } else {
+            processTopmostModelInputDataNodeWithoutClashingNames(context, topmostInputName,
+                                                                 topmostModelTuple, model);
+        }
+    }
+
+    static void processTopmostModelInputDataNodeWithClashingNames(DMNContext context, String topmostInputName,
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNRuntimeUtils.java:94]: Important change

**Review by baldimir — APPROVED** [review]

**Review by yesamer — APPROVED** [review]
