### PR TITLE
[incubator-kie-issues#1382] Fix identifier retrieval for quoted strings

### LINKED ISSUE #1382: Fix single quote parsing in drl files
The string 
`"Question with ' s"` 
is not parsed correctly, because the `s` after the single quote is interpreted as identifier inside [StringUtils.extractFirstIdentifier](https://github.com/apache/incubator-kie-drools/blob/c9dd8290be198dcc92bf0d193e0b0649926f742a/drools-core/src/main/java/org/drools/core/util/StringUtils.java#L973)

As comparison, the following one works as expected
`"Question with ' :"`
but only because the  `:` after the single quote is not interpreted as identifier.

Scope of the ticket is to refactor the [StringUtils.extractFirstIdentifier](https://github.com/apache/incubator-kie-drools/blob/c9dd8290be198dcc92bf0d193e0b0649926f742a/drools-core/src/main/java/org/drools/core/util/StringUtils.java#L979) method to correctly manage the different use case.
Also provide unittest for the method

### PR DESCRIPTION
**Pull request by gitgabrio**
Fixes https://github.com/apache/incubator-kie-issues/issues/1382

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

### CODE REVIEW

File: drools-util/src/main/java/org/drools/util/StringUtils.java [hunk 1]
```diff
@@ -964,22 +964,40 @@ public static String extractFirstIdentifier(String string, int start) {
         return builder.toString();
     }
 
+    /**
+     * Method that tries to extract <b>identifiers</b> from a Srting.
```
Comment (yesamer) [inline drools-util/src/main/java/org/drools/util/StringUtils.java:968]: typo

**Review by yesamer — APPROVED** [review]
LGTM

**Review by mariofusco — APPROVED** [review]
