### PR TITLE
[incubator-kie-issues#2178] handle functionItem in ItemDefinition 

### LINKED ISSUE #2178: Handle functionItem in ItemDefinition During DMN Compilation
When a functionItem is present inside any itemDefinition in a DMN model, the current compilation process fails to identify and retrieve its type. This happens because the case for handling functionItem is not implemented in the compilation logic.
The DMN versions (≥ 1.3) support getFunctionItem() and this need to be handled in the compilation logic.
This ticket aims to ensure that the type reference for functionItem is correctly retrieved and processed.

[1157-implicit-conversions-test-01.xml](https://github.com/user-attachments/files/23792164/1157-implicit-conversions-test-01.xml)
[1157-implicit-conversions.txt](https://github.com/user-attachments/files/23792163/1157-implicit-conversions.txt)

### PR DESCRIPTION
**Pull request by AthiraHari77**
Closes : https://github.com/apache/incubator-kie-issues/issues/2178
This PR aims to ensure that the type reference for functionItem is correctly retrieved and processed.

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

### CODE REVIEW

File: kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesSorter.java [hunk 1]
```diff
@@ -57,46 +58,55 @@ public List<ItemDefinition> sort(List<ItemDefinition> ins) {
...
-    private static boolean recurseFind(ItemDefinition o1, QName qname2) {
+    private static boolean recurseFind(ItemDefinition o1, QName qname2, DMNVersion dmnVersion) {
         if ( o1.getTypeRef() != null ) {
-            return extFastEqUsingNSPrefix(o1, qname2);
+            return extFastEqUsingNSPrefix(o1, o1.getTypeRef(), qname2);
+        }
+        if (dmnVersion != null && dmnVersion.getDmnVersion() > DMNVersion.V1_2.getDmnVersion()) {
+            FunctionItem fi = o1.getFunctionItem();
+            if (fi != null && fi.getOutputTypeRef() != null) {
+                return extFastEqUsingNSPrefix(o1, o1.getFunctionItem().getOutputTypeRef(), qname2);
```
[the remark this answers is not in the document]
Comment (gitgabrio) [reply kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesSorter.java]: Could you please apply, @AthiraHari77  ?

File: kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesSorter.java [hunk 2]
```diff
@@ -37,66 +38,80 @@ public ItemDefinitionDependenciesSorter(String modelNamespace) {
...
      */
-    public List<ItemDefinition> sort(List<ItemDefinition> ins) {
+    public List<ItemDefinition> sort(List<ItemDefinition> itemDefinitions, DMNVersion dmnVersion) {
         // In a graph A -> B -> {C, D}
         // showing that A requires B, and B requires C,D
         // then a depth-first visit would satisfy required ordering, for example a valid depth first visit is also a valid sort here: C, D, B, A.
-        Collection<ItemDefinition> visited = new ArrayList<>(ins.size());
-        List<ItemDefinition> dfv = new ArrayList<>(ins.size());
+        Collection<ItemDefinition> visited = new ArrayList<>(itemDefinitions.size());
+        List<ItemDefinition> sortedItemDefinitions = new ArrayList<>(itemDefinitions.size());
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesSorter.java:48]: 👍

File: kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesSorter.java [hunk 3]
```diff
@@ -37,66 +38,80 @@ public ItemDefinitionDependenciesSorter(String modelNamespace) {
...
 
-        for (ItemDefinition node : ins) {
+        for (ItemDefinition node : itemDefinitions) {
             if (!visited.contains(node)) {
-                dfVisit(node, ins, visited, dfv);
+                populateSortedItemDefinitions(node, itemDefinitions, visited, sortedItemDefinitions, dmnVersion);
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesSorter.java:52]: ❤️

File: kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesSorter.java [hunk 4]
```diff
@@ -37,66 +38,80 @@ public ItemDefinitionDependenciesSorter(String modelNamespace) {
...
+
+    static QName retrieveTypeRef(ItemDefinition o1, DMNVersion dmnVersion) {
         if ( o1.getTypeRef() != null ) {
-            return extFastEqUsingNSPrefix(o1, qname2);
+            return o1.getTypeRef();
         }
-        for ( ItemDefinition ic : o1.getItemComponent() ) {
-            if ( recurseFind(ic, qname2) ) {
-                return true;
+        if (dmnVersion != null && dmnVersion.getDmnVersion() > DMNVersion.V1_2.getDmnVersion()) {
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesSorter.java]: Hi @AthiraHari77 : what about -> 

```java
QName toReturn = o1.getTypeRef();
        if (toReturn == null 
          && dmnVersion.getDmnVersion() > DMNVersion.V1_2.getDmnVersion()
          && o1.getFunctionItem() != null) {
            toReturn = o1.getFunctionItem().getOutputTypeRef();
        }
        return toReturn;
```
(we should avoid the `dmnVersion != null ` check because, it it is null, then there is a bug somewhere else, and we should be aware of that)
?

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java [hunk 5]
```diff
@@ -227,4 +230,53 @@ void circular3() {
...
+
+        QName result = retrieveTypeRef(item, DMNVersion.V1_2);
+        assertThat(result).isNull();
+    }
+
+    @Test
+    void testRetrieveTypeRef_dmnVersionNull() {
+        ItemDefinition item = new TItemDefinition();
+
+        QName result = retrieveTypeRef(item, null);
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java]: As in other comment, dmn version should never be `null`.
If you saw that during debug, it means there is a bug somewhere (and an exception should be thrown)

**Review by gitgabrio — COMMENTED** [review]
Great job @AthiraHari77 !
Only minor details left...

File: kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesSorter.java (hunk 4 above)
Comment (AthiraHari77) [reply kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesSorter.java]: @gitgabrio There are few tests which failed because dmnVersion appear to be null for those.

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java (hunk 5 above)
Comment (AthiraHari77) [reply kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java]: @gitgabrio **getStandardFEELDialectURIS** inside class FEELDialect was not updated for dmn version 1.6, hence all those models belonging to this version showed dmnversion as null.

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java [hunk 6]
```diff
@@ -51,7 +52,7 @@ private void addComponent(ItemDefinition i, String componentName) {
     }
 
     private List<ItemDefinition> orderingStrategy(final List<ItemDefinition> ins) {
-        return new ItemDefinitionDependenciesSorter(TEST_NS).sort(ins);
+        return new ItemDefinitionDependenciesSorter(TEST_NS).sort(ins, DMNVersion.V1_2);
     }
```
[the remark this answers is not in the document]
Comment (yesamer) [reply kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java:58]: @AthiraHari77 Can you please consider, if feasible,  to unit test that scenario too?

**Review by yesamer — APPROVED** [review]

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java (hunk 5 above)
Comment (yesamer) [reply kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java]: @AthiraHari77 Nice catch!!

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (AthiraHari77) [reply kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java:58]: Done

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java [hunk 7]
```diff
@@ -227,4 +230,66 @@ void circular3() {
...
+
+        QName result = retrieveTypeRef(item, TEST_NS, DMNVersion.V1_2);
+        assertThat(result).isNull();
+    }
+
+    @Test
+    void testRetrieveTypeRefFromFunctionItem() {
+        ItemDefinition id = new TItemDefinition();
+        FunctionItem fi = new TFunctionItem();
+        QName type = new QName("ns", "date");
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java]: Hi @AthiraHari77 
I've the impression that this `"ns"` should be replaced by `TEST_NS` (IINW, the two are the same "by chance")

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java [hunk 8]
```diff
@@ -227,4 +230,66 @@ void circular3() {
...
+        id.setFunctionItem(fi);
+        QName result = retrieveTypeRef(id, TEST_NS, DMNVersion.V1_3);
+        assertThat(type).isEqualTo(result);
+    }
+
+    @Test
+    void retrieveTypeRef_withUnsupportedDMNVersion() {
+        ItemDefinition id = new TItemDefinition();
+        FunctionItem fi = new TFunctionItem();
+        QName type = new QName("ns", "date");
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java]: Same comment above

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java (hunk 7 above)
Comment (AthiraHari77) [reply kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/ItemDefinitionDependenciesTest.java]: Fixed
