### PR TITLE
[Incubator kie issues#2099 continuation] BFEEL Redesign and  Refactoring

### LINKED ISSUE #2099: DMN Runner returns wrong values for B-FEEL expressions
using the DMN Runner and these B-FEEL expressions user is getting wrong results.

- day of week("a") : throws an error about non existing function instead of ""
- split("abc", 22) : throws an error 'FEEL_EVALUATION_ERROR: FEEL ERROR while evaluating literal expression 'split("abc", 22)': Unable to find function 'split( lass org.kie.dmn.feel.runtime.functions.SplitFunctio )'' instead of []
- "Today is " + today() : returns null instead of "Today is 202x-xx-xx"
- "The result is: " + 1 : returns null instead of "The result is: 1"
- 5 + " minutes" : returns null instead of "5 minutes"
- "This is " + null : returns null instead of "This is "
- 1 + null : returns null instead of 1
- null - 6 : returns null instead of -6
- date("2021-01-01") + 7 : throws error 'FEEL_EVALUATION_ERROR: FEEL ERROR while evaluating literal expression 'date("2021-01-01") + 7': Based on the specification, the operation is undefined for the specified parameter set.' instead of 7
- "abc" - 2 : returns null instead of ""
- 22 * "a" : returns null instead of 0
- null / 22 : returns null instead of  0
- duration("P1Y") * null : returns null instead of duration("P0M")

For trying those expressions, this model can be used:

[bfeel-tests.dmn.txt](https://github.com/user-attachments/files/22299604/bfeel-tests.dmn.txt)

One of reported cases demonstrated also as screenshot

Image

### PR DESCRIPTION
**Pull request by ChinchuAjith**
Fixes https://github.com/apache/incubator-kie-issues/issues/2099

This PR will refactor the executor classes to use a strategy‑based design for dialect operations

**Background**
Previously, all executor classes contained large chains of if/else statements to handle different operand types and dialect rules. This led to:

- Highly polluted and hard‑to‑read code
- Duplication of logic across executors
- Difficulty in extending or maintaining dialect‑specific behavior

**Changes Introduced**

- Implemented a strategy pattern for operation handling:
- Introduced a DialectHandler interface that defines all supported operations (add, subtract, multiply, divide, equality, etc.).
- Created FEELDialectHandler and BFEELDialectHandler classes to encapsulate dialect‑specific semantics.
- Added a factory to select the appropriate dialect handler at runtime.
- Moved common operation logic into shared maps  to reduce duplication.
- Used CheckedPredicate + BiFunction maps instead of nested conditionals, making operation dispatch declarative and extensible.
- Ensured proper event notification  for invalid or undefined operations (e.g., division by zero).

**Benefits**

- Cleaner, more maintainable codebase (no more long if/else chains).
- Clear separation of common logic vs. dialect‑specific overrides.
- Easier to extend with new dialects or operations in the future.
- Improved readability and testability of executor classes.

### CODE REVIEW

**Comment by yesamer** [comment]
@ChinchuAjith Could you please  add a description of the changes? Thanks.

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java [hunk 1]
```diff
@@ -0,0 +1,292 @@
...
+                (left, right) -> ""
+        );
+        map.putAll(getCommonSubOperations(ctx));
+        return map;
+    }
+
+    /**
+     * Builds the BFeel specific 'Multiplication' operations.
+     * @param ctx : Current Evaluation context
+     * @return : a Map of CheckedPredicate to BiFunction representing the BFeel specific 'Multiplicationj' operations
```
[the remark this answers is not in the document]
Comment (ChinchuAjith) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java]: Done

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/DefaultDialectHandler.java [hunk 2]
```diff
@@ -0,0 +1,666 @@
...
+                (left, right) -> ((Temporal) right).plus((TemporalAmount) left)
+        );
+
+        // TemporalAmount + ChronoPeriod
+        map.put(
+                new CheckedPredicate((left, right) -> left instanceof TemporalAmount && right instanceof ChronoPeriod, false),
+                (left, right) -> ((ChronoPeriod) right).plus((TemporalAmount) left)
+        );
+
+        // nleft or right -> null
```
[the remark this answers is not in the document]
Comment (ChinchuAjith) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/DefaultDialectHandler.java]: Done

File: kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/ast/InfixOperatorTest.java [hunk 3]
```diff
@@ -74,6 +79,18 @@ void addLocalDateAndDuration() {
...
+    //TODO : Added for testing purpose. Need to move to Bfeel specific test class
+    @Test
+    void addStringAndNumber_shouldReturnConcatenatedString() {
+        FEELEventListenersManager manager = new FEELEventListenersManager();
+        EvaluationContextImpl ctx = new EvaluationContextImpl(ClassLoaderUtil.findDefaultClassLoader(), manager, FEELDialect.BFEEL, DMNVersion.getLatest());
+        String left = "Total: ";
+        Integer right = 100;
+        Object result = InfixOperator.ADD.evaluate(left, right, ctx);
+        assertThat(result).isEqualTo("Total: 100");
+        //assertThat(result).isNull();
```
[the remark this answers is not in the document]
Comment (ChinchuAjith) [reply kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/ast/InfixOperatorTest.java]: Removed as the test is not required.

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/InfixExecutorUtils.java [hunk 4]
```diff
@@ -76,7 +79,48 @@ public static Object and(Object left, Object right, EvaluationContext ctx) {
...
+     */
+    public static void commonManageInvalidParameters(final EvaluationContext ctx) {
+        FEELEvent.Severity severity = ctx.getFEELDialect().equals(FEELDialect.BFEEL) ? FEELEvent.Severity.WARN
+                : FEELEvent.Severity.ERROR;
+        ctx.notifyEvt(() -> new InvalidParametersEvent(severity, Msg.OPERATION_IS_UNDEFINED_FOR_PARAMETERS.getMask()));
+    }
+
+    public static BigDecimal getBigDecimal(Object object, EvaluationContext ctx) {
+        if (ctx.getFEELDialect().equals(FEELDialect.BFEEL)) {
+            if (! (object instanceof Number)) {
```
[the remark this answers is not in the document]
Comment (ChinchuAjith) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/InfixExecutorUtils.java]: Done

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/OrExecutor.java [hunk 5]
```diff
@@ -47,7 +48,7 @@ public Object evaluate(InfixOpNode infixNode, EvaluationContext ctx) {
             if (!leftOR.booleanValue()) {
                 return BooleanEvalHelper.getBooleanOrDialectDefault(infixNode.getRight().evaluate(ctx), ctx.getFEELDialect());
             } else {
-                return Boolean.TRUE; //left hand operand is true, we do not need to evaluate right side
+                return Boolean.TRUE; //No need to evaluate right side
```
[the remark this answers is not in the document]
Comment (ChinchuAjith) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/OrExecutor.java]: Done

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/DivExecutor.java [hunk 6]
```diff
@@ -48,55 +36,12 @@ public static DivExecutor instance() {
 
     @Override
     public Object evaluate(Object left, Object right, EvaluationContext ctx) {
-        return div(left, right, ctx);
+        DialectHandler handler = DialectHandlerFactory.getHandler(ctx);
+        return handler.executeDivision(left, right, ctx);
     }
 
-    @Override
+   @Override
```
[the remark this answers is not in the document]
Comment (ChinchuAjith) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/DivExecutor.java]: Done

File: kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/ast/InfixOperatorTest.java [hunk 7]
```diff
@@ -23,7 +23,12 @@
 import java.time.temporal.ChronoUnit;
 
 import org.junit.jupiter.api.Test;
+import org.kie.dmn.api.core.DMNVersion;
 import org.kie.dmn.feel.lang.EvaluationContext;
+import org.kie.dmn.feel.lang.FEELDialect;
+import org.kie.dmn.feel.lang.impl.EvaluationContextImpl;
+import org.kie.dmn.feel.lang.impl.FEELEventListenersManager;
+import org.kie.dmn.feel.util.ClassLoaderUtil;
```
Comment (yesamer) [inline kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/ast/InfixOperatorTest.java]: @ChinchuAjith Are those imports necessary?

File: kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/BFEELTest.java [hunk 8]
```diff
@@ -50,60 +52,64 @@ protected void instanceTest(String expression, Object result, FEELEvent.Severity
...
-
-                {"number(\"test\", null, null)", BigDecimal.ZERO, null},
-                {"number(\"1234\", null, null)", BigDecimal.valueOf(1234), null},
-                {"number(\"1 234 000\", \" \" , null)", BigDecimal.valueOf(1234000), null},
-                {"number(\"1,234\", \",\" , null)", BigDecimal.valueOf(1234), null},
+        final Object[][] cases = new Object[][] { { "\"a\" = 1", false, null }, { "\"a\" != 1", true, null },
+                { "\"a\" < 1", false, null }, { "\"a\" <= null", false, null }, { "\"a\" > 1", false, null },
+                { "null >= 1", false, null }, { "not(\"a\")", false, null }, { "true and \"x\"", false, null },
+                { "false or \"x\"", false, null }, { "\"a\" in [1..100]", false, null },
+                { "null between 1 and 100", false, FEELEvent.Severity.WARN },
```
Comment (yesamer) [inline kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/BFEELTest.java:60]: @ChinchuAjith If I'm not wrong, it looks like this file you changed the formatting only. Why that? I would suggest keeping the original formatting if there is no specific reason to change it.

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java [hunk 9]
```diff
@@ -0,0 +1,292 @@
...
+ * under the License.
+ */
+package org.kie.dmn.feel.lang.ast.dialectHandlers;
+
+import org.kie.dmn.feel.lang.EvaluationContext;
+import org.kie.dmn.feel.lang.FEELDialect;
+import org.kie.dmn.feel.lang.types.impl.ComparablePeriod;
+import org.kie.dmn.feel.util.BooleanEvalHelper;
+
+import java.math.BigDecimal;
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java:21]: Hi @ChinchuAjith 
Some unneeded imports, here

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/GteExecutor.java [hunk 10]
```diff
@@ -37,9 +36,9 @@ public static GteExecutor instance() {
 
     @Override
     public Object evaluate(Object left, Object right, EvaluationContext ctx) {
-        return or(BooleanEvalHelper.compare(left, right, ctx.getFEELDialect(), (l, r) -> l.compareTo(r) > 0),
-                  BooleanEvalHelper.isEqual(left, right, ctx.getFEELDialect()),
-                  ctx); // do not use Java || to avoid potential NPE due to FEEL 3vl.
+
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/GteExecutor.java]: Hi @ChinchuAjith 
PLease remove empty line here

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/OrExecutor.java
Comment (gitgabrio) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/OrExecutor.java]: This also should be managed by DialectHandler

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/AndExecutor.java [hunk 11]
```diff
@@ -37,23 +37,21 @@ public static AndExecutor instance() {
...
-        if (leftAND != null) {
-            if (leftAND.booleanValue()) {
-                return BooleanEvalHelper.getBooleanOrDialectDefault(infixNode.getRight().evaluate(ctx),
-                                                                    ctx.getFEELDialect());
-            } else {
-                return Boolean.FALSE; //left hand operand is false, we do not need to evaluate right side
-            }
-        } else {
-            return BooleanEvalHelper.getFalseOrDialectDefault(infixNode.getRight().evaluate(ctx), ctx.getFEELDialect());
+        Object leftRaw = infixNode.getLeft().evaluate(ctx);
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/AndExecutor.java]: This also should be managed by DialectHandler

File: kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/ast/infixexecutors/InfixExecutorUtilsTest.java [hunk 12]
```diff
@@ -21,26 +21,37 @@
...
+import java.time.LocalDateTime;
+import java.time.Period;
+import java.time.temporal.TemporalField;
 import java.util.ArrayList;
+import java.util.Arrays;
 import java.util.List;
 import java.util.Random;
 import java.util.function.BinaryOperator;
+import java.util.function.Consumer;
 import java.util.function.Supplier;
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/ast/infixexecutors/InfixExecutorUtilsTest.java:32]: Please check unneeded imports here

**Review by gitgabrio — COMMENTED** [review]
Hi @ChinchuAjith 
Thanks for PR - there are just minor things left to fix

File: kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/ast/InfixOperatorTest.java (hunk 7 above)
Comment (ChinchuAjith) [reply kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/ast/InfixOperatorTest.java]: Removed unused imports

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java (hunk 9 above)
Comment (ChinchuAjith) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java:21]: Removed

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/GteExecutor.java (hunk 10 above)
Comment (ChinchuAjith) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/GteExecutor.java]: Done

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/OrExecutor.java
Comment (ChinchuAjith) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/OrExecutor.java]: Done

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/AndExecutor.java (hunk 11 above)
Comment (ChinchuAjith) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/infixexecutors/AndExecutor.java]: Done

File: kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/ast/infixexecutors/InfixExecutorUtilsTest.java (hunk 12 above)
Comment (ChinchuAjith) [reply kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/ast/infixexecutors/InfixExecutorUtilsTest.java:32]: Done

**Review by yesamer — APPROVED** [review]

File: kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/BFEELTest.java (hunk 8 above)
Comment (yesamer) [reply kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/BFEELTest.java:60]: @ChinchuAjith I still see those formatting changes, are they needed?

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java [hunk 13]
```diff
@@ -0,0 +1,326 @@
...
+
+        // Special case: otherwise AND true → false
+        map.put(
+                new CheckedPredicate((left, right) -> {
+                    Boolean leftBool = BooleanEvalHelper.getBooleanOrDialectDefault(left, dialect);
+                    Object rightValue = evalRight(right, ctx);
+                    Boolean rightBool = BooleanEvalHelper.getBooleanOrDialectDefault(rightValue, dialect);
+                    return leftBool == null && Boolean.TRUE.equals(rightBool);
+                }, false),
+                (left, right) -> Boolean.FALSE
```
[the remark this answers is not in the document]
Comment (yesamer) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java]: This comment is wrong, please ignore it.

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java [hunk 14]
```diff
@@ -0,0 +1,326 @@
...
+        map.put(
+                new CheckedPredicate((left, right) -> {
+                    Boolean leftBool = BooleanEvalHelper.getBooleanOrDialectDefault(left, dialect);
+                    Object rightValue = evalRight(right, ctx);
+                    Boolean rightBool = BooleanEvalHelper.getBooleanOrDialectDefault(rightValue, dialect);
+                    return leftBool == null && Boolean.FALSE.equals(rightBool);
+                }, false),
+                (left, right) -> Boolean.FALSE
+        );
+        map.putAll(getCommonAddOperations(ctx));
```
[the remark this answers is not in the document]
Comment (yesamer) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java]: @ChinchuAjith This could makes sense, can you please double-check?

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java [hunk 15]
```diff
@@ -0,0 +1,326 @@
...
+     * @return : a Map of CheckedPredicate to BiFunction representing the BFeel specific 'Substraction' operations
+     */
+    @Override
+    public Map<CheckedPredicate, BiFunction<Object, Object, Object>> getSubOperations(EvaluationContext ctx) {
+        Map<CheckedPredicate, BiFunction<Object, Object, Object>> map = new LinkedHashMap<>();
+        //subtraction with Strings → empty string
+        map.put(
+                new CheckedPredicate((left, right) ->
+                                (left instanceof String || right instanceof String), false),
+                (left, right) -> ""
```
[the remark this answers is not in the document]
Comment (yesamer) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java]: Please ignore this comment.

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/BooleanEvalHelper.java [hunk 16]
```diff
@@ -286,4 +289,15 @@ static Boolean isEqualObject(Object l, Object r) {
...
+    // Evaluate right operand if it’s a node
+    public static Object evalRight(Object right, EvaluationContext ctx) {
+        if (right instanceof InfixOpNode) {
+            return ((InfixOpNode) right).evaluate(ctx);
+        } else if (right instanceof BaseNode) {
+            return ((BaseNode) right).evaluate(ctx);
+        } else {
+            return right;
+        }
+    }
```
[the remark this answers is not in the document]
Comment (ChinchuAjith) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/BooleanEvalHelper.java]: Moved to the handler.

**Review by gitgabrio — APPROVED** [review]
Thanks @ChinchuAjith LGTM!

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (ChinchuAjith) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java]: This has been corrected. It was added accidently

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java [hunk 17]
```diff
@@ -0,0 +1,326 @@
...
+                (left, right) -> Boolean.FALSE
+        );
+
+        // Special case: otherwise AND otherwise → false
+        map.put(
+                new CheckedPredicate((left, right) -> {
+                    Boolean leftBool = BooleanEvalHelper.getBooleanOrDialectDefault(left, dialect);
+                    Object rightValue = evalRight(right, ctx);
+                    Boolean rightBool = BooleanEvalHelper.getBooleanOrDialectDefault(rightValue, dialect);
+                    return leftBool == null && Boolean.FALSE.equals(rightBool);
```
[the remark this answers is not in the document]
Comment (ChinchuAjith) [reply kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/dialectHandlers/BFEELDialectHandler.java:113]: If otherwise or null is passed to the getBooleanOrDialectDefault method, it returns false because the dialect is Bfeel. This confirms the check is functioning as intended
