### PR TITLE
[Incubator-kie-issues#1820] Resolve "Missing Conditional element" runtime exception during model execution

### LINKED ISSUE #1820: Resolve "Missing Conditional element" runtime exception during model execution
During DMN model execution, the following runtime exception "**Missing Conditional element inside org.kie.dmn.model.v1_5.TDecision@3d4d3fe7**" is being thrown.
Attached below is the sample dmn file to reproduce the same.

[Fail_Validation.txt](https://github.com/user-attachments/files/18733122/Fail_Validation.txt)

### PR DESCRIPTION
**Pull request by AthiraHari77**
Fixes https://github.com/apache/incubator-kie-issues/issues/1820

This PR aims to fix the runtime exception "Missing Conditional element inside model" thrown while executing a dmn model which has a conditional event present.

<summary>
How to replicate CI configuration locally?
</summary>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/6257 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6257/2/display/redirect

**Test results:**
- PASSED: 23172
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6257/2/testReport/org.kie.dmn.core.impl/DMNRuntimeEventManagerUtilsTest/testConditionalEvent/">org.kie.dmn.core.impl.DMNRuntimeEventManagerUtilsTest.testConditionalEvent</a></summary>
Failed to find file ConditionalEvent.dmn
</details>

**Comment by kie-ci3** [comment]
**PR job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/6257 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6257/4/display/redirect

**Test results:**
- PASSED: 23173
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6257/4/testReport/org.kie.dmn.core.compiler/DMNEvaluatorCompilerTest/testCompileConditional/">org.kie.dmn.core.compiler.DMNEvaluatorCompilerTest.testCompileConditional</a></summary>
Failed to find file ConditionalEvent.dmn
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6257/4/testReport/org.kie.dmn.core.impl/DMNRuntimeEventManagerUtilsTest/testConditionalEvent/">org.kie.dmn.core.impl.DMNRuntimeEventManagerUtilsTest.testConditionalEvent</a></summary>
Failed to find file ConditionalEvent.dmn
</details>

**Comment by kie-ci3** [comment]
**PR job** `#5` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/6257 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6257/5/display/redirect

**Test results:**
- PASSED: 23173
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6257/5/testReport/org.kie.dmn.core.compiler/DMNEvaluatorCompilerTest/testCompileConditional/">org.kie.dmn.core.compiler.DMNEvaluatorCompilerTest.testCompileConditional</a></summary>
Failed to find file ConditionalEvent.dmn
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6257/5/testReport/org.kie.dmn.core.impl/DMNRuntimeEventManagerUtilsTest/testConditionalEvent/">org.kie.dmn.core.impl.DMNRuntimeEventManagerUtilsTest.testConditionalEvent</a></summary>
Failed to find file ConditionalEvent.dmn
</details>

File: kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNConditionalEvaluator.java [hunk 1]
```diff
@@ -31,44 +34,81 @@
...
-    private DMNExpressionEvaluator elseEvaluator;
-    private DMNElement node;
-    private String name;
-    private final Map<DMNExpressionEvaluator, String> evaluatorIdMap = new HashMap<>();
+    private final DMNExpressionEvaluator ifEvaluator;
+    private final DMNExpressionEvaluator thenEvaluator;
+    private final DMNExpressionEvaluator elseEvaluator;
+    private final DMNElement node;
+    private final String name;
+    private final Map<EvaluatorIdentifier, DMNExpressionEvaluator> evaluatorIdMap;
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNConditionalEvaluator.java]: Hi @AthiraHari77 
this seems unused: could u please remove if so ?

File: kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNConditionalEvaluator.java [hunk 2]
```diff
@@ -94,7 +134,9 @@ protected EvaluatorResult manageBooleanOrNullIfResult(Boolean booleanResult, DMN
         DMNExpressionEvaluator evaluatorToUse = booleanResult != null && booleanResult ? thenEvaluator : elseEvaluator;
 
         EvaluatorResult toReturn = evaluatorToUse.evaluate(eventManager, result);
-        String executedId  = evaluatorIdMap.get(evaluatorToUse);
+
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNConditionalEvaluator.java]: Could you please remove those empty lines ?

File: kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNEvaluatorCompiler.java [hunk 3]
```diff
@@ -1035,37 +1048,39 @@ private java.util.List<UnaryTest> textToUnaryTestList(DMNCompilerContext ctx, St
         return ctx.getFeelHelper().evaluateUnaryTests(ctx, text, model, element, errorMsg, msgParams);
     }
 
-    private DMNExpressionEvaluator compileConditional(DMNCompilerContext ctx, DMNModelImpl model, DMNBaseNode node,
-                                                      String exprName, Conditional expression) {
-        DMNExpressionEvaluator ifEvaluator = compileExpression(ctx, model, node, exprName + " [if]",
+    protected DMNExpressionEvaluator compileConditional(DMNCompilerContext ctx, DMNModelImpl model, DMNBaseNode node,
+                                              String exprName, Conditional expression) {
+        DMNExpressionEvaluator ifEvaluator = compileExpression(ctx, model, node, exprName + " [" + DMNConditionalEvaluator.EvaluatorType.IF.name().toLowerCase() + "]",
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNEvaluatorCompiler.java]: Please, do not use that

`(enum).name().toLowerCase()`

construct.
Whenever there is a String to be bound to an enum, it is better to define it as specific property of the enum itself, so that the twos are independent.
See, as example, [UnaryOperator](https://github.com/apache/incubator-kie-drools/blob/d27006e40f4e9f7f0c2203fdf1b0b16f8e930a9d/kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/ast/UnaryTestNode.java#L41)

File: kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNEvaluatorCompiler.java [hunk 4]
```diff
@@ -1035,37 +1048,39 @@ private java.util.List<UnaryTest> textToUnaryTestList(DMNCompilerContext ctx, St
...
                                                                expression.getIf().getExpression());
-        DMNExpressionEvaluator thenEvaluator = compileExpression(ctx, model, node, exprName + " [then]",
+        DMNExpressionEvaluator thenEvaluator = compileExpression(ctx, model, node, exprName + " [" + DMNConditionalEvaluator.EvaluatorType.THEN.name().toLowerCase() + "]",
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNEvaluatorCompiler.java]: This 
`exprName + " [" + (enum).name().toLowerCase() + "]"`
is replicated, and could also be replaced with a String.format: could you please create a specific method for that, to 
1. avoid replication
2. have only one single point of modification, if needed ?
Thanks!

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/ast/DMNConditionalEvaluatorTest.java [hunk 5]
```diff
@@ -172,4 +162,35 @@ void manageBooleanOrNullIfResultWithNull() {
...
+    }
+
+    @Test
+    void testGetEvaluatorIdentifier() {
+        Map<DMNConditionalEvaluator.EvaluatorType, DMNConditionalEvaluator.EvaluatorIdentifier> evaluatorIdentifierMap = new HashMap<>();
+        evaluatorIdentifierMap.put(DMNConditionalEvaluator.EvaluatorType.IF, ifIdentifier);
+        evaluatorIdentifierMap.put(DMNConditionalEvaluator.EvaluatorType.THEN, thenIdentifier);
+        evaluatorIdentifierMap.put(DMNConditionalEvaluator.EvaluatorType.ELSE, elseIdentifier);
+
+        DMNConditionalEvaluator.EvaluatorIdentifier resultIf = DMNConditionalEvaluator.getEvaluatorIdentifier(evaluatorIdentifierMap, DMNConditionalEvaluator.EvaluatorType.IF);
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/ast/DMNConditionalEvaluatorTest.java]: Lines from 182 to 187 could be compacted with a loop over evaluatorIdentifierMap and a one-line assertion: could you please refactor it ?

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/ast/DMNConditionalEvaluatorTest.java [hunk 6]
```diff
@@ -172,4 +162,35 @@ void manageBooleanOrNullIfResultWithNull() {
...
+        assertThat(resultIf).isEqualTo(ifIdentifier);
+        assertThat(resultThen).isEqualTo(thenIdentifier);
+        assertThat(resultElse).isEqualTo(elseIdentifier);
+    }
+
+    @Test
+    void testMissingEvaluatorIdentifier() {
+        Map<DMNConditionalEvaluator.EvaluatorType, DMNConditionalEvaluator.EvaluatorIdentifier> evaluatorIdentifierMap = new HashMap<>();
+        String errorMessage = "Missing THEN evaluator in evaluatorIdMap";
+        assertThatRuntimeException().isThrownBy(() -> DMNConditionalEvaluator.getEvaluatorIdentifier(evaluatorIdentifierMap, DMNConditionalEvaluator.EvaluatorType.THEN)).withMessage(errorMessage);
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/ast/DMNConditionalEvaluatorTest.java:190]: 👍  ❤️

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/DMNEvaluatorCompilerTest.java [hunk 7]
```diff
@@ -81,10 +106,97 @@ void getFEELDialectAdaptedFEELWrongExpressionLanguage() {
...
+        assertThat(dmnRuntime).isNotNull();
+        String nameSpace = "https://kie.org/dmn/_5B448C78-0DBF-4554-92A4-8C0247EB01FD";
+
+        final DMNModel dmnModel = dmnRuntime.getModel(nameSpace, "DMN_00DF4B93-0243-4813-BA70-A1894AC723BE");
+        assertThat(dmnModel).isNotNull();
+        DMNModelInstrumentedBase retrieved = getNodeById(dmnModel, "_096DC616-A4D5-449C-A350-491E42F3C8FB");
+        Conditional expr = (Conditional) retrieved;
+        DMNBaseNode dmnBaseNode = getNodeByName(dmnModel, "B");
+        DMNType numType = dmnBaseNode.getType();
+        DMN_COMPILER_CONTEXT.enterFrame();
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/DMNEvaluatorCompilerTest.java]: There are some issues here
1. DMN_COMPILER_CONTEXT is a static member; whatever modification is done to it, it will be propagated to other test, potentially breaking them
2. this DMN_COMPILER_CONTEXT is not even the same used during runtime instantiation, so there is no relationship with it
3. I'm not sure about the need of the "enterFrame()" invocation but, a) there is not an exitFrame() b) it may have side effects c) I think is not needed at all

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/DMNEvaluatorCompilerTest.java [hunk 8]
```diff
@@ -81,10 +106,97 @@ void getFEELDialectAdaptedFEELWrongExpressionLanguage() {
...
+                .fromResources(Collections.singletonList(resource)).getOrElseThrow(RuntimeException::new);
+        assertThat(dmnRuntime).isNotNull();
+        String nameSpace = "https://kie.org/dmn/_5B448C78-0DBF-4554-92A4-8C0247EB01FD";
+
+        final DMNModel dmnModel = dmnRuntime.getModel(nameSpace, "DMN_00DF4B93-0243-4813-BA70-A1894AC723BE");
+        assertThat(dmnModel).isNotNull();
+        DMNModelInstrumentedBase retrieved = getNodeById(dmnModel, "_096DC616-A4D5-449C-A350-491E42F3C8FB");
+        DMNBaseNode dmnBaseNode = getNodeByName(dmnModel, "B");
+        DMNType numType = dmnBaseNode.getType();
+        DMN_COMPILER_CONTEXT.enterFrame();
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/DMNEvaluatorCompilerTest.java]: See previous comment about usage of static property DMN_COMPILER_CONTEXT

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/DMNEvaluatorCompilerTest.java [hunk 9]
```diff
@@ -81,10 +106,97 @@ void getFEELDialectAdaptedFEELWrongExpressionLanguage() {
...
+
+        Resource resource = ResourceFactory.newClassPathResource("valid_models/DMNv1_5/ConditionalEvent.dmn");
+        DMNRuntime dmnRuntime = DMNRuntimeBuilder.fromDefaults().buildConfiguration()
+                .fromResources(Collections.singletonList(resource)).getOrElseThrow(RuntimeException::new);
+        assertThat(dmnRuntime).isNotNull();
+        String nameSpace = "https://kie.org/dmn/_5B448C78-0DBF-4554-92A4-8C0247EB01FD";
+
+        final DMNModel dmnModel = dmnRuntime.getModel(nameSpace, "DMN_00DF4B93-0243-4813-BA70-A1894AC723BE");
+        assertThat(dmnModel).isNotNull();
+        DMNModelInstrumentedBase retrieved = getNodeById(dmnModel, "_096DC616-A4D5-449C-A350-491E42F3C8FB");
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/DMNEvaluatorCompilerTest.java:126]: Please assert that retrieved is not null

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/DMNEvaluatorCompilerTest.java [hunk 10]
```diff
@@ -81,10 +106,97 @@ void getFEELDialectAdaptedFEELWrongExpressionLanguage() {
...
+        String exprName = "testExpression";
+        Resource resource = ResourceFactory.newClassPathResource("valid_models/DMNv1_5/ConditionalEvent.dmn");
+        DMNRuntime dmnRuntime = DMNRuntimeBuilder.fromDefaults().buildConfiguration()
+                .fromResources(Collections.singletonList(resource)).getOrElseThrow(RuntimeException::new);
+        assertThat(dmnRuntime).isNotNull();
+        String nameSpace = "https://kie.org/dmn/_5B448C78-0DBF-4554-92A4-8C0247EB01FD";
+
+        final DMNModel dmnModel = dmnRuntime.getModel(nameSpace, "DMN_00DF4B93-0243-4813-BA70-A1894AC723BE");
+        assertThat(dmnModel).isNotNull();
+        DMNModelInstrumentedBase retrieved = getNodeById(dmnModel, "_096DC616-A4D5-449C-A350-491E42F3C8FB");
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/DMNEvaluatorCompilerTest.java:169]: Please assert that retrieved is not null

File: kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/impl/DMNRuntimeEventManagerUtilsTest.java [hunk 11]
```diff
@@ -77,4 +86,20 @@ void fireAfterConditionalEvaluation() {
         assertThat(evaluateConditionalEvent.getEvaluatorResultResult()).isEqualTo(evaluatorResult);
         assertThat(evaluateConditionalEvent.getExecutedId()).isEqualTo(executedId);
     }
+
+    @Test
+    void testConditionalEvent() {
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/impl/DMNRuntimeEventManagerUtilsTest.java:98]: The scope of this class is to the the Events that are fired during execution - see previous test.
Here, it does not matter the final result of the execution, but we have to verify that expected events (in that case `AfterEvaluateConditionalEvent` ) have actually been fired, with expected values

**Review by gitgabrio — CHANGES_REQUESTED** [review]
Thanks for the PR, @AthiraHari77 !
There are minor things to be fixed, but anyway good job!

**Comment by AthiraHari77** [comment]
@gitgabrio I have updated the PR with the changes requested. Please take a look.

**Comment by kie-ci3** [comment]
**PR job** `#8` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/6257 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6257/8/display/redirect

**Test results:**
- PASSED: 23185
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6257/8/testReport/org.kie.dmn.core.impl/DMNRuntimeEventManagerUtilsTest/fireAfterConditionalEvaluation/">org.kie.dmn.core.impl.DMNRuntimeEventManagerUtilsTest.fireAfterConditionalEvaluation</a></summary>
<br/>dMNRuntimeEventListener.afterConditionalEvaluation(<br/>    <Capturing argument: AfterConditionalEvaluationEvent><br/>);<br/>Wanted 1 time:<br/>-> at org.kie.dmn.api.core.event.DMNRuntimeEventListener.afterConditionalEvaluation(DMNRuntimeEventListener.java:61)<br/>But was 2 times:<br/>-> at org.kie.dmn.core.impl.DMNRuntimeEventManagerUtils.lambda$fireAfterConditionalEvaluation$15(DMNRuntimeEventManagerUtils.java:165)<br/>-> at org.kie.dmn.core.impl.DMNRuntimeEventManagerUtils.lambda$fireAfterConditionalEvaluation$15(DMNRuntimeEventManagerUtils.java:165)<br/><br/>
</details>

**Comment by jomarko** [comment]
Thank you for this PR!

**Review by gitgabrio — APPROVED** [review]
Great job, @AthiraHari77 Thx!

**Review by yesamer — APPROVED** [review]
Thank you @AthiraHari77
