### PR TITLE
[Incubator kie issues#1743]Return a list of dates instead of a range

### LINKED ISSUE #1743: Return a list of dates instead of a range
There is a DMN TCK failure, when running with Drools:

[ERROR] 0084-feel-for-loops-test-01.decision_024 – Time elapsed: 0.001 s <<< ERROR!
java.lang.RuntimeException: ERROR: FAILURE: 'decision_024' expected='[1980-01-01, 1980-01-02, 1980-01-03]' but found='[[ 1980-01-01 .. 1980-01-03 ]]'

The test is located here (1). Based on the error, it looks like that Drools is returning a range instead of a list in this test case.

Reading the [specs#10.3.2.14 For loop expression](https://www.omg.org/spec/DMN/1.6/Beta1/PDF), it seems that a `for` iteration should always return a list

> The result of the for loop expression is a list containing the result of the evaluation of the expression e for each
individual iteration in order

Options how to debug:

Replicating the test case directly in Drools repository, so it gets a proper stack trace pointing to the code path being executed, to be able to see the code areas, which may need a fix. 

A specific unit test is required to test the modification in isolation.
In case of `for` expression, the class to test is `ForExpressionNode`, and there is already a unit-test class for it, [ForExpressionNodeTest](https://github.com/apache/incubator-kie-drools/blob/84eb420b3026935c56f4c41e3d8fa9aeb41ae0cb/kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/ast/ForExpressionNodeTest.java)

In the past we used to add cases to "FEEL" test classes, but the problem with that approach are:
1. the test involve bringing up all the FEEL compiler stack, so it can be influenced by lot of factors that are not relevant to the modification itself
2. due to the above, debugging those tests is time-consuming and cumbersome while, at the end of the day, the actual code to verify is the method in the "Node" itself
3. the above has a direct effect on the time required to deliver the feature and, on bigger scale, on the time spent in the CI.

To execute and eventually debug in isolation a single tck test, a small hack is required inside the TCK test suite, i.e. to add a "filter" in the [DroolsTCKTest#addTestCasesFolders](https://github.com/dmn-tck/tck/blob/5a40dc510f9cf9788fbc04cb4a79eb9a7c235e10/runners/dmn-tck-runner-drools/src/test/java/org/omg/dmn/tck/runner/drools/DroolsTCKTest.java#L96) method

~~If the test case is mainly just a FEEL expression (FEEL is a language used to write expressions in DMN), the FEEL expression could be added to a test class, e.g. this one (2), so it can be run in isolation.~~
 

(1) https://github.com/dmn-tck/tck/tree/master/TestCases/compliance-level-3/0084-feel-for-loops

~~(2) https://github.com/apache/incubator-kie-drools/blob/053d70c8f9145706e771f90e8ce2dafa3899b59b/kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/FEELConditionsAndLoopsTest.java#L31~~

### PR DESCRIPTION
**Pull request by AthiraHari77**
Fixes https://github.com/apache/incubator-kie-issues/issues/1743

This PR resolves the issue in DMN TCK where ranges were not being evaluated correctly. With this fix, ranges are now evaluated properly, and a list of dates is returned instead of a range.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

### CODE REVIEW

**Review by gitgabrio — APPROVED** [review]
Thanks @AthiraHari77 LGTM!  👍

File: kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/ast/forexpressioniterators/ForIterationUtilsTest.java [hunk 1]
```diff
@@ -148,4 +153,55 @@ void validateValuesFalseTest() {
...
+
+    @Test
+    void testGetForIterationRangeValues() {
+        Range range = new RangeImpl(Range.RangeBoundary.CLOSED, BigDecimal.TEN, BigDecimal.valueOf(20), Range.RangeBoundary.OPEN);
+        EvaluationContext ctx = mock(EvaluationContext.class);
+
+        ForIteration expectedResult = new ForIteration("rangeTest", null);
+        ForIteration actualResult = getForIteration(range, "rangeTest", ctx);
+        assertThat(actualResult).isNotNull();
+        assertEquals(actualResult.toString(), expectedResult.toString());
```
Comment (pibizza) [inline kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/ast/forexpressioniterators/ForIterationUtilsTest.java]: Please do not use assertEquals. Assertj assertions are standard inside drools code.

Comment (AthiraHari77) [reply kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/ast/forexpressioniterators/ForIterationUtilsTest.java]: Fixed, updated the testcases.

**Review by baldimir — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/6223 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/3/display/redirect

**Test results:**
- PASSED: 22778
- FAILED: 7

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/3/testReport/org.kie.dmn.feel.lang.ast.forexpressioniterators/ForIterationUtilsTest/getForIterationNotValidTest/">org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtilsTest.getForIterationNotValidTest</a></summary>
<br/>Expecting actual throwable to be an instance of:<br/>  org.kie.dmn.feel.exceptions.EndpointOfRangeNotValidTypeException<br/>but was:<br/>  org.kie.dmn.feel.exceptions.EndpointOfForIterationNotValidTypeException<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.valueMustBeValid(ForIterationUtils.java:62)<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.validateValues(ForIterationUtils.java:55)<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.getForIteration(ForIterationUtils.java:37)<br/> ...(74 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/3/testReport/org.kie.dmn.feel.lang.ast.forexpressioniterators/ForIterationUtilsTest/validateValuesFalseTest/">org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtilsTest.validateValuesFalseTest</a></summary>
<br/>Expecting actual throwable to be an instance of:<br/>  org.kie.dmn.feel.exceptions.EndpointOfRangeNotValidTypeException<br/>but was:<br/>  org.kie.dmn.feel.exceptions.EndpointOfForIterationNotValidTypeException<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.valueMustBeValid(ForIterationUtils.java:62)<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.validateValues(ForIterationUtils.java:55)<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtilsTest.validateValuesFalseTest(ForIterationUtilsTest.java:127)<br/> ...(73 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/3/testReport/org.kie.dmn.feel.lang.ast.forexpressioniterators/ForIterationUtilsTest/valueMustBeValidFalseTest/">org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtilsTest.valueMustBeValidFalseTest</a></summary>
<br/>Expecting actual throwable to be an instance of:<br/>  org.kie.dmn.feel.exceptions.EndpointOfRangeNotValidTypeException<br/>but was:<br/>  org.kie.dmn.feel.exceptions.EndpointOfForIterationNotValidTypeException<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.valueMustBeValid(ForIterationUtils.java:62)<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtilsTest.valueMustBeValidFalseTest(ForIterationUtilsTest.java:108)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> ...(72 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/3/testReport/org.kie.dmn.feel.runtime/FEEL12ExtendedForLoopTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[9]/">org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[9]</a></summary>
org.kie.dmn.feel.exceptions.EndpointOfForIterationDifferentTypeException<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.validateValues(ForIterationUtils.java:53)<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.getForIteration(ForIterationUtils.java:37)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.createForIteration(ForExpressionNode.java:146)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.populateToReturn(ForExpressionNode.java:103)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.evaluate(ForExpressionNode.java:85)<br/>	at org.kie.dmn.feel.lang.impl.CompiledExpressionImpl.apply(CompiledExpressionImpl.java:49)<br/>	at org.kie.dmn.feel.lang.impl.InterpretedExecutableExpression.apply(InterpretedExecutableExpression.java:40)<br/>	at org.kie.dmn.feel.lang.impl.InterpretedExecutableExpression.apply(InterpretedExecutableExpression.java:26)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:96)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:39)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:156)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:148)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:124)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.assertResult(BaseFEELTest.java:89)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.expression(BaseFEELTest.java:74)<br/>	at org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(FEEL12ExtendedForLoopTest.java:45)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/3/testReport/org.kie.dmn.feel.runtime/FEEL12ExtendedForLoopTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[10]/">org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[10]</a></summary>
org.kie.dmn.feel.exceptions.EndpointOfForIterationDifferentTypeException<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.validateValues(ForIterationUtils.java:53)<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.getForIteration(ForIterationUtils.java:37)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.createForIteration(ForExpressionNode.java:146)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.populateToReturn(ForExpressionNode.java:103)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.evaluate(ForExpressionNode.java:85)<br/>	at org.kie.dmn.feel.codegen.feel11.gen902e779e9b4f422495f4844979c88e4d.TemplateCompiledFEELExpression.apply(TemplateCompiledFEELExpression.java:36)<br/>	at org.kie.dmn.feel.codegen.feel11.gen902e779e9b4f422495f4844979c88e4d.TemplateCompiledFEELExpression.apply(TemplateCompiledFEELExpression.java:26)<br/>	at org.kie.dmn.feel.lang.impl.CompiledExecutableExpression.apply(CompiledExecutableExpression.java:34)<br/>	at org.kie.dmn.feel.lang.impl.CompiledExecutableExpression.apply(CompiledExecutableExpression.java:24)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:96)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:39)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:156)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:148)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:124)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.assertResult(BaseFEELTest.java:89)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.expression(BaseFEELTest.java:74)<br/>	at org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(FEEL12ExtendedForLoopTest.java:45)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/3/testReport/org.kie.dmn.feel.runtime/FEEL12ExtendedForLoopTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[21]/">org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[21]</a></summary>
org.kie.dmn.feel.exceptions.EndpointOfForIterationDifferentTypeException<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.validateValues(ForIterationUtils.java:53)<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.getForIteration(ForIterationUtils.java:37)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.createForIteration(ForExpressionNode.java:146)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.populateToReturn(ForExpressionNode.java:103)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.evaluate(ForExpressionNode.java:85)<br/>	at org.kie.dmn.feel.lang.ast.ContextEntryNode.evaluate(ContextEntryNode.java:70)<br/>	at org.kie.dmn.feel.lang.ast.ContextNode.evaluate(ContextNode.java:79)<br/>	at org.kie.dmn.feel.lang.impl.CompiledExpressionImpl.apply(CompiledExpressionImpl.java:49)<br/>	at org.kie.dmn.feel.lang.impl.InterpretedExecutableExpression.apply(InterpretedExecutableExpression.java:40)<br/>	at org.kie.dmn.feel.lang.impl.InterpretedExecutableExpression.apply(InterpretedExecutableExpression.java:26)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:96)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:39)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:156)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:148)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:124)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.assertResult(BaseFEELTest.java:89)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.expression(BaseFEELTest.java:74)<br/>	at org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(FEEL12ExtendedForLoopTest.java:45)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/3/testReport/org.kie.dmn.feel.runtime/FEEL12ExtendedForLoopTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[22]/">org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[22]</a></summary>
org.kie.dmn.feel.exceptions.EndpointOfForIterationDifferentTypeException<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.validateValues(ForIterationUtils.java:53)<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.getForIteration(ForIterationUtils.java:37)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.createForIteration(ForExpressionNode.java:146)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.populateToReturn(ForExpressionNode.java:103)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.evaluate(ForExpressionNode.java:85)<br/>	at org.kie.dmn.feel.lang.ast.ContextEntryNode.evaluate(ContextEntryNode.java:70)<br/>	at org.kie.dmn.feel.lang.ast.ContextNode.evaluate(ContextNode.java:79)<br/>	at org.kie.dmn.feel.codegen.feel11.gen47b2b88379974214989da35eee190ab4.TemplateCompiledFEELExpression.apply(TemplateCompiledFEELExpression.java:36)<br/>	at org.kie.dmn.feel.codegen.feel11.gen47b2b88379974214989da35eee190ab4.TemplateCompiledFEELExpression.apply(TemplateCompiledFEELExpression.java:26)<br/>	at org.kie.dmn.feel.lang.impl.CompiledExecutableExpression.apply(CompiledExecutableExpression.java:34)<br/>	at org.kie.dmn.feel.lang.impl.CompiledExecutableExpression.apply(CompiledExecutableExpression.java:24)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:96)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:39)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:156)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:148)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:124)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.assertResult(BaseFEELTest.java:89)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.expression(BaseFEELTest.java:74)<br/>	at org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(FEEL12ExtendedForLoopTest.java:45)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>
</details>

**Review by yesamer — APPROVED** [review]
Thank you @AthiraHari77 !

**Comment by yesamer** [comment]
@AthiraHari77 Unfortunately the CI reported 7 test failures, can you please check it?

**Comment by kie-ci3** [comment]
**PR job** `#6` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/6223 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/6/display/redirect

**Test results:**
- PASSED: 23097
- FAILED: 7

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/6/testReport/org.kie.dmn.feel.lang.ast.forexpressioniterators/ForIterationUtilsTest/getForIterationNotValidTest/">org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtilsTest.getForIterationNotValidTest</a></summary>
<br/>Expecting actual throwable to be an instance of:<br/>  org.kie.dmn.feel.exceptions.EndpointOfRangeNotValidTypeException<br/>but was:<br/>  org.kie.dmn.feel.exceptions.EndpointOfForIterationNotValidTypeException<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.valueMustBeValid(ForIterationUtils.java:62)<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.validateValues(ForIterationUtils.java:55)<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.getForIteration(ForIterationUtils.java:37)<br/> ...(74 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/6/testReport/org.kie.dmn.feel.lang.ast.forexpressioniterators/ForIterationUtilsTest/validateValuesFalseTest/">org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtilsTest.validateValuesFalseTest</a></summary>
<br/>Expecting actual throwable to be an instance of:<br/>  org.kie.dmn.feel.exceptions.EndpointOfRangeNotValidTypeException<br/>but was:<br/>  org.kie.dmn.feel.exceptions.EndpointOfForIterationNotValidTypeException<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.valueMustBeValid(ForIterationUtils.java:62)<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.validateValues(ForIterationUtils.java:55)<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtilsTest.validateValuesFalseTest(ForIterationUtilsTest.java:127)<br/> ...(73 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/6/testReport/org.kie.dmn.feel.lang.ast.forexpressioniterators/ForIterationUtilsTest/valueMustBeValidFalseTest/">org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtilsTest.valueMustBeValidFalseTest</a></summary>
<br/>Expecting actual throwable to be an instance of:<br/>  org.kie.dmn.feel.exceptions.EndpointOfRangeNotValidTypeException<br/>but was:<br/>  org.kie.dmn.feel.exceptions.EndpointOfForIterationNotValidTypeException<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.valueMustBeValid(ForIterationUtils.java:62)<br/> at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtilsTest.valueMustBeValidFalseTest(ForIterationUtilsTest.java:108)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> ...(72 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/6/testReport/org.kie.dmn.feel.runtime/FEEL12ExtendedForLoopTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[9]/">org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[9]</a></summary>
org.kie.dmn.feel.exceptions.EndpointOfForIterationDifferentTypeException<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.validateValues(ForIterationUtils.java:53)<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.getForIteration(ForIterationUtils.java:37)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.createForIteration(ForExpressionNode.java:144)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.populateToReturn(ForExpressionNode.java:101)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.evaluate(ForExpressionNode.java:83)<br/>	at org.kie.dmn.feel.lang.impl.CompiledExpressionImpl.apply(CompiledExpressionImpl.java:49)<br/>	at org.kie.dmn.feel.lang.impl.InterpretedExecutableExpression.apply(InterpretedExecutableExpression.java:40)<br/>	at org.kie.dmn.feel.lang.impl.InterpretedExecutableExpression.apply(InterpretedExecutableExpression.java:26)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:96)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:39)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:156)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:148)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:124)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.assertResult(BaseFEELTest.java:89)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.expression(BaseFEELTest.java:74)<br/>	at org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(FEEL12ExtendedForLoopTest.java:45)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/6/testReport/org.kie.dmn.feel.runtime/FEEL12ExtendedForLoopTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[10]/">org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[10]</a></summary>
org.kie.dmn.feel.exceptions.EndpointOfForIterationDifferentTypeException<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.validateValues(ForIterationUtils.java:53)<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.getForIteration(ForIterationUtils.java:37)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.createForIteration(ForExpressionNode.java:144)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.populateToReturn(ForExpressionNode.java:101)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.evaluate(ForExpressionNode.java:83)<br/>	at org.kie.dmn.feel.codegen.feel11.gene7ccae2139474b2ab4fc4acb00120f8f.TemplateCompiledFEELExpression.apply(TemplateCompiledFEELExpression.java:36)<br/>	at org.kie.dmn.feel.codegen.feel11.gene7ccae2139474b2ab4fc4acb00120f8f.TemplateCompiledFEELExpression.apply(TemplateCompiledFEELExpression.java:26)<br/>	at org.kie.dmn.feel.lang.impl.CompiledExecutableExpression.apply(CompiledExecutableExpression.java:34)<br/>	at org.kie.dmn.feel.lang.impl.CompiledExecutableExpression.apply(CompiledExecutableExpression.java:24)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:96)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:39)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:156)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:148)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:124)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.assertResult(BaseFEELTest.java:89)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.expression(BaseFEELTest.java:74)<br/>	at org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(FEEL12ExtendedForLoopTest.java:45)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/6/testReport/org.kie.dmn.feel.runtime/FEEL12ExtendedForLoopTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[21]/">org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[21]</a></summary>
org.kie.dmn.feel.exceptions.EndpointOfForIterationDifferentTypeException<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.validateValues(ForIterationUtils.java:53)<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.getForIteration(ForIterationUtils.java:37)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.createForIteration(ForExpressionNode.java:144)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.populateToReturn(ForExpressionNode.java:101)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.evaluate(ForExpressionNode.java:83)<br/>	at org.kie.dmn.feel.lang.ast.ContextEntryNode.evaluate(ContextEntryNode.java:70)<br/>	at org.kie.dmn.feel.lang.ast.ContextNode.evaluate(ContextNode.java:79)<br/>	at org.kie.dmn.feel.lang.impl.CompiledExpressionImpl.apply(CompiledExpressionImpl.java:49)<br/>	at org.kie.dmn.feel.lang.impl.InterpretedExecutableExpression.apply(InterpretedExecutableExpression.java:40)<br/>	at org.kie.dmn.feel.lang.impl.InterpretedExecutableExpression.apply(InterpretedExecutableExpression.java:26)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:96)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:39)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:156)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:148)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:124)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.assertResult(BaseFEELTest.java:89)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.expression(BaseFEELTest.java:74)<br/>	at org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(FEEL12ExtendedForLoopTest.java:45)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6223/6/testReport/org.kie.dmn.feel.runtime/FEEL12ExtendedForLoopTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[22]/">org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[22]</a></summary>
org.kie.dmn.feel.exceptions.EndpointOfForIterationDifferentTypeException<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.validateValues(ForIterationUtils.java:53)<br/>	at org.kie.dmn.feel.lang.ast.forexpressioniterators.ForIterationUtils.getForIteration(ForIterationUtils.java:37)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.createForIteration(ForExpressionNode.java:144)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.populateToReturn(ForExpressionNode.java:101)<br/>	at org.kie.dmn.feel.lang.ast.ForExpressionNode.evaluate(ForExpressionNode.java:83)<br/>	at org.kie.dmn.feel.lang.ast.ContextEntryNode.evaluate(ContextEntryNode.java:70)<br/>	at org.kie.dmn.feel.lang.ast.ContextNode.evaluate(ContextNode.java:79)<br/>	at org.kie.dmn.feel.codegen.feel11.gen57a87600f2b649fa8b9d0105c36d70e7.TemplateCompiledFEELExpression.apply(TemplateCompiledFEELExpression.java:36)<br/>	at org.kie.dmn.feel.codegen.feel11.gen57a87600f2b649fa8b9d0105c36d70e7.TemplateCompiledFEELExpression.apply(TemplateCompiledFEELExpression.java:26)<br/>	at org.kie.dmn.feel.lang.impl.CompiledExecutableExpression.apply(CompiledExecutableExpression.java:34)<br/>	at org.kie.dmn.feel.lang.impl.CompiledExecutableExpression.apply(CompiledExecutableExpression.java:24)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:96)<br/>	at org.kie.dmn.feel.codegen.feel11.ProcessedExpression.apply(ProcessedExpression.java:39)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:156)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:148)<br/>	at org.kie.dmn.feel.lang.impl.FEELImpl.evaluate(FEELImpl.java:124)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.assertResult(BaseFEELTest.java:89)<br/>	at org.kie.dmn.feel.runtime.BaseFEELTest.expression(BaseFEELTest.java:74)<br/>	at org.kie.dmn.feel.runtime.FEEL12ExtendedForLoopTest.instanceTest(FEEL12ExtendedForLoopTest.java:45)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>
</details>
