### PR TITLE
[incubator-kie-drools-5745] Compatibility issue with Spring-boot 3.2

### LINKED ISSUE #5745: Compatibility issue with Spring-boot 3.2
I am opening this issue so the others could be aware when upgrading to spring-boot 3.2.

On spring-boot, it was added [nested jar support](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#nested-jar-support), it seems that this causes problem when Kie needs to find kmodule.xml

logs of the problem:

```
2024-02-26T15:37:23.303Z  INFO 1 --- [microservice-x] [  XNIO-1 task-2] o.d.c.k.b.impl.ClasspathKieProject       : Found kmodule: jar:nested:/srv/app.jar/!BOOT-INF/lib/x-module-0.0.1-SNAPSHOT-plain.jar!/META-INF/kmodule.xml
2024-02-26T15:37:23.619Z  WARN 1 --- [microservice-x] [  XNIO-1 task-2] o.d.c.k.b.impl.ClasspathKieProject       : Unable to find pom.properties in /srv/app.jar/!BOOT-INF/lib/x-module-0.0.1-SNAPSHOT-plain.jar
2024-02-26T15:37:23.621Z  WARN 1 --- [microservice-x] [  XNIO-1 task-2] o.d.c.k.b.impl.ClasspathKieProject       : As folder project tried to fall back to pom.xml, but could not find one
2024-02-26T15:37:23.621Z  WARN 1 --- [microservice-x] [  XNIO-1 task-2] o.d.c.k.b.impl.ClasspathKieProject       : Unable to load pom.properties from/srv/app.jar/!BOOT-INF/lib/x-module-0.0.1-SNAPSHOT-plain.jar
2024-02-26T15:37:23.621Z  WARN 1 --- [microservice-x] [  XNIO-1 task-2] o.d.c.k.b.impl.ClasspathKieProject       : Cannot find maven pom properties for this project. Using the container's default ReleaseId
2024-02-26T15:37:23.623Z  INFO 1 --- [microservice-x] [  XNIO-1 task-2] o.d.c.k.b.i.InternalKieModuleProvider    : Creating KieModule for artifact org.default:artifact:1.0.0
2024-02-26T15:37:23.645Z ERROR 1 --- [microservice-x] [  XNIO-1 task-2] o.d.c.k.b.impl.ClasspathKieProject       : Unable to build index of kmodule.xml url=jar:nested:/srv/app.jar/!BOOT-INF/lib/x-module-0.0.1-SNAPSHOT-plain.jar!/META-INF/kmodule.xml Range [57, 56) out of bounds for length 56
2024-02-26T15:37:23.652Z ERROR 1 --- [microservice-x] [  XNIO-1 task-2] x.d.ExceptionHandler    : RuntimeException java.lang.RuntimeException: Cannot find a default KieSession
```

after adding the option bellow on `build.gradle` 

```gradle
bootJar {
  loaderImplementation = org.springframework.boot.loader.tools.LoaderImplementation.CLASSIC
}
```

logs after applying the `LoaderImplementation.CLASSIC`
```
2024-02-26T15:48:52.940Z  INFO 1 --- [microservice-x] [  XNIO-1 task-2] o.d.c.k.b.impl.ClasspathKieProject       : Found kmodule: jar:file:/srv/app.jar!/BOOT-INF/lib/x-module-0.0.1-SNAPSHOT-plain.jar!/META-INF/kmodule.xml
2024-02-26T15:48:53.269Z  WARN 1 --- [microservice-x] [  XNIO-1 task-2] o.d.c.k.b.impl.ClasspathKieProject       : Unable to load pom.properties from/srv/app.jar!/BOOT-INF/lib/x-module-0.0.1-SNAPSHOT-plain.jar
2024-02-26T15:48:53.269Z  WARN 1 --- [microservice-x] [  XNIO-1 task-2] o.d.c.k.b.impl.ClasspathKieProject       : Cannot find maven pom properties for this project. Using the container's default ReleaseId
2024-02-26T15:48:53.271Z  INFO 1 --- [microservice-x] [  XNIO-1 task-2] o.d.c.k.b.i.InternalKieModuleProvider    : Creating KieModule for artifact org.default:artifact:1.0.0
2024-02-26T15:48:53.285Z  INFO 1 --- [microservice-x] [  XNIO-1 task-2] o.d.c.kie.builder.impl.KieContainerImpl  : Start creation of KieBase: defaultKieBase
2024-02-26T15:48:54.647Z  INFO 1 --- [microservice-x] [  XNIO-1 task-2] o.d.c.kie.builder.impl.KieContainerImpl  : End creation of KieBase: defaultKieBase
```

### PR DESCRIPTION
**Pull request by tkobayas**
**Issue**:
* https://github.com/apache/incubator-kie-drools/issues/5745

### CODE REVIEW

File: drools-util/src/test/java/org/drools/util/JarUtilsTest.java [hunk 1]
```diff
@@ -29,4 +29,16 @@ public void normalizeSpringBootResourceUrlPath() {
...
+    public void replaceNestedPathForSpringBoot32_shouldNotAffectOldPath() {
+        String result = JarUtils.replaceNestedPathForSpringBoot32("/dir/myapp.jar!/BOOT-INF/lib/mykjar.jar");
+        assertThat(result).isEqualTo("/dir/myapp.jar!/BOOT-INF/lib/mykjar.jar");
+    }
+
+    @Test
+    public void replaceNestedPathForSpringBoot32_shouldReplaceNewPath() {
+        String result = JarUtils.replaceNestedPathForSpringBoot32("/dir/myapp.jar/!BOOT-INF/lib/mykjar.jar");
+        assertThat(result).isEqualTo("/dir/myapp.jar!/BOOT-INF/lib/mykjar.jar");
+    }
```
Comment (tkobayas) [inline drools-util/src/test/java/org/drools/util/JarUtilsTest.java:43]: Added simple unit tests only.

I have manually tested with spring boot 3.2.6 uber jar. https://github.com/tkobayas/kiegroup-examples/tree/master/Ex-spring-boot-3.2-demo-main . and confirmed that the issue is solved.

Adding such integration tests (actually build a uber jar and run it with `ProcessBuilder`) might be worth discussing.

**Review by mariofusco — APPROVED** [review]

**Review by pibizza — APPROVED** [review]
