### PR TITLE
[incubator-kie-issues-1752] TCK failure-Lambda function returns null

### LINKED ISSUE #1752: Lambda function returns null
**TCK Test 0092-feel-lambda - 014**

"compliance-level-3/0092-feel-lambda","0092-feel-lambda-test-01","014","ERROR","FAILURE: 'decision_014_1' expected='25.0' but found='null'"

Model: https://github.com/dmn-tck/tck/blob/a113546e37653dfc9e49284ead1ed49d43fe9d6e/TestCases/compliance-level-3/0092-feel-lambda/0092-feel-lambda.dmn#L487
Test: https://github.com/dmn-tck/tck/blob/a113546e37653dfc9e49284ead1ed49d43fe9d6e/TestCases/compliance-level-3/0092-feel-lambda/0092-feel-lambda-test-01.xml#L146

Double check why only one single test of this group fails

Consider this Decision node

```
<decision name="decision_014_1" id="_decision_014_1">
        <variable name="decision_014_1"/>
        <knowledgeRequirement>
            <requiredKnowledge href="#_bkm_014_1"/>
        </knowledgeRequirement>
        <!-- passed built-in functions as params  -->
        <literalExpression>
            <text>bkm_014_1(abs, sqrt)</text>
        </literalExpression>
    </decision>
```

It results in the following error:

> 14:13:47.511 [main] WARN  org.kie.dmn.core.util.MsgUtil.logMessage:84 - Parameter 'fn1' is of type 'DMNType{ http://www.montera.com.au/spec/DMN/0092-feel-lambda : lambda_number_returns_number }' but the actual value 'org.kie.dmn.feel.runtime.functions.AbsFunction@7153995c' is not an instance of that type; setting as null
> 14:13:47.512 [main] WARN  org.kie.dmn.core.util.MsgUtil.logMessage:84 - Parameter 'fn2' is of type 'DMNType{ http://www.montera.com.au/spec/DMN/0092-feel-lambda : lambda_number_returns_number }' but the actual value 'org.kie.dmn.feel.runtime.functions.SqrtFunction@3b256d50' is not an instance of that type; setting as null
> 14:13:47.512 [main] ERROR org.kie.dmn.core.util.MsgUtil.logMessage:83 - FEEL ERROR while evaluating literal expression 'fn1(-5)*fn2(25)': Not an invocable: 'null'
> 14:13:47.512 [main] ERROR org.kie.dmn.core.util.MsgUtil.logMessage:83 - FEEL ERROR while evaluating literal expression 'fn1(-5)*fn2(25)': Not an invocable: 'null'

### PR DESCRIPTION
**Pull request by bncriju**
Fixes https://github.com/apache/incubator-kie-issues/issues/1752

Related PR: https://github.com/apache/incubator-kie-kogito-runtimes/pull/3860

Added the fix for this problem and added test class and test methods to verify the same.

After and before the changes:

< "compliance-level-3/0092-feel-lambda","0092-feel-lambda-test-01","014","SUCCESS",""

> "compliance-level-3/0092-feel-lambda","0092-feel-lambda-test-01","014","ERROR","FAILURE: 'decision_014_1' expected='25.0' but found='null'"

### CODE REVIEW

File: kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/types/GenFnTypeTest.java [hunk 1]
```diff
@@ -0,0 +1,208 @@
+package org.kie.dmn.feel.lang.types;
```
Comment (yesamer) [inline kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/types/GenFnTypeTest.java:20]: @bncriju Please add the Apache header in this new class

Comment (bncriju) [reply kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/types/GenFnTypeTest.java:20]: Thanks @yesamer. Will add it now.

Comment (bncriju) [reply kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/types/GenFnTypeTest.java:20]: Done adding the same.

**Review by baldimir — APPROVED** [review]

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/types/GenFnType.java [hunk 2]
```diff
@@ -1,4 +1,5 @@
-/**
+/*
+ *
```
Comment (yesamer) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/types/GenFnType.java]: @bncriju Please remove line 2

File: kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/types/GenFnTypeTest.java [hunk 3]
```diff
@@ -0,0 +1,228 @@
+/*
+ *
```
Comment (yesamer) [inline kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/lang/types/GenFnTypeTest.java]: @bncriju Please remove line 2

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/types/GenFnType.java [hunk 4]
```diff
@@ -40,18 +41,15 @@ public GenFnType(List<Type> argsGen, Type returnGen) {
...
-        if (o instanceof FEELFunction) {
-            FEELFunction oFn = (FEELFunction) o;
-            List<List<Param>> signatures = oFn.getParameters().stream().filter(signature -> signature.size() == argsGen.size()).collect(Collectors.toList());
-            for (List<Param> signature : signatures) {
-                if (signature.size() == argsGen.size() && IntStream.range(0, argsGen.size()).allMatch(i -> argsGen.get(i).conformsTo(signature.get(i).type))) {
-                    return true;
-                }
+        if (o instanceof FEELFunction oFn) {
+            List<List<Param>> parameters = oFn.getParameters();
+            if(parameters.isEmpty()){
```
Comment (yesamer) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/types/GenFnType.java]:
```suggestion
            if (parameters.isEmpty()) {
```
Please use the same formatting style of the code base

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/types/GenFnType.java [hunk 5]
```diff
@@ -69,13 +67,22 @@ public String getName() {
...
     public boolean conformsTo(Type t) {
-        if (t instanceof GenFnType) {
-            GenFnType fnT = (GenFnType) t;
+        if (t instanceof GenFnType fnT) {
             return fnT.argsGen.size() == this.argsGen.size() &&
-                   IntStream.range(0, argsGen.size()).allMatch(i -> fnT.argsGen.get(i).conformsTo(this.argsGen.get(i))) &&
-                   this.returnGen.conformsTo(fnT.returnGen);
+                    IntStream.range(0, argsGen.size()).allMatch(i -> fnT.argsGen.get(i).conformsTo(this.argsGen.get(i))) &&
+                    this.returnGen.conformsTo(fnT.returnGen);
         } else {
```
Comment (yesamer) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/types/GenFnType.java:74]: @bncriju Please remove those  2 whitespaces

**Review by yesamer — COMMENTED** [review]
Minor points to address (formatting)

File: kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/types/GenFnType.java [hunk 6]
```diff
@@ -40,18 +41,15 @@ public GenFnType(List<Type> argsGen, Type returnGen) {
...
-            List<List<Param>> signatures = oFn.getParameters().stream().filter(signature -> signature.size() == argsGen.size()).collect(Collectors.toList());
-            for (List<Param> signature : signatures) {
-                if (signature.size() == argsGen.size() && IntStream.range(0, argsGen.size()).allMatch(i -> argsGen.get(i).conformsTo(signature.get(i).type))) {
-                    return true;
-                }
+        if (o instanceof FEELFunction oFn) {
+            List<List<Param>> parameters = oFn.getParameters();
+            if(parameters.isEmpty()){
+                //this is used to consider function as parameter
+                return true;
```
Comment (gitgabrio) [inline kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/lang/types/GenFnType.java]: HI @bncriju 
on second thought, I think we need to implement more check here, i.e. if the expected input/output of the current GenFnType are compatible with invoke methods of the provided function

**Comment by kie-ci3** [comment]
**PR job** `#8` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/6261 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6261/8/display/redirect

**Test results:**
- PASSED: 23224
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6261/8/testReport/org.kie.dmn.feel.lang.types/GenFnTypeTest/testIsInstanceOfWithNoParameters/">org.kie.dmn.feel.lang.types.GenFnTypeTest.testIsInstanceOfWithNoParameters</a></summary>
<br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6261/8/testReport/org.kie.dmn.feel.lang.types/GenFnTypeTest/testIsAssignableValueWithFunction/">org.kie.dmn.feel.lang.types.GenFnTypeTest.testIsAssignableValueWithFunction</a></summary>
<br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6261/8/testReport/org.kie.dmn.feel.lang.types/GenFnTypeTest/testIsInstanceOfWithMatchingFunctionSignature/">org.kie.dmn.feel.lang.types.GenFnTypeTest.testIsInstanceOfWithMatchingFunctionSignature</a></summary>
<br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6261/8/testReport/org.kie.dmn.feel.runtime.functions/BaseFEELFunctionTest/testIsCompatible/">org.kie.dmn.feel.runtime.functions.BaseFEELFunctionTest.testIsCompatible</a></summary>
<br/>Expecting value to be true but was false
</details>

**Comment by kie-ci3** [comment]
**PR job** `#11` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/6261 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6261/11/display/redirect

**Test results:**
- PASSED: 22368
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6261/11/testReport/org.kie.dmn.feel.lang.types/GenFnTypeTest/testIsInstanceOfWithNoParameters/">org.kie.dmn.feel.lang.types.GenFnTypeTest.testIsInstanceOfWithNoParameters</a></summary>
<br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6261/11/testReport/org.kie.dmn.feel.lang.types/GenFnTypeTest/testIsAssignableValueWithFunction/">org.kie.dmn.feel.lang.types.GenFnTypeTest.testIsAssignableValueWithFunction</a></summary>
<br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6261/11/testReport/org.kie.dmn.feel.lang.types/GenFnTypeTest/testIsInstanceOfWithMatchingFunctionSignature/">org.kie.dmn.feel.lang.types.GenFnTypeTest.testIsInstanceOfWithMatchingFunctionSignature</a></summary>
<br/>Expecting value to be true but was false
</details>

**Comment by kie-ci3** [comment]
**PR job** `#12` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/6261 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6261/12/display/redirect

**Test results:**
- PASSED: 23238
- FAILED: 3

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6261/12/testReport/org.kie.dmn.feel.lang.types/GenFnTypeTest/testIsInstanceOfWithNoParameters/">org.kie.dmn.feel.lang.types.GenFnTypeTest.testIsInstanceOfWithNoParameters</a></summary>
<br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6261/12/testReport/org.kie.dmn.feel.lang.types/GenFnTypeTest/testIsAssignableValueWithFunction/">org.kie.dmn.feel.lang.types.GenFnTypeTest.testIsAssignableValueWithFunction</a></summary>
<br/>Expecting value to be true but was false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6261/12/testReport/org.kie.dmn.feel.lang.types/GenFnTypeTest/testIsInstanceOfWithMatchingFunctionSignature/">org.kie.dmn.feel.lang.types.GenFnTypeTest.testIsInstanceOfWithMatchingFunctionSignature</a></summary>
<br/>Expecting value to be true but was false
</details>

**Comment by kie-ci3** [comment]
**PR job** `#17` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/6261 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6261/17/display/redirect

**Test results:**
- PASSED: 23245
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6261/17/testReport/org.kie.dmn.feel.runtime.functions/BaseFEELFunctionTest/testIsCompatibleTrue/">org.kie.dmn.feel.runtime.functions.BaseFEELFunctionTest.testIsCompatibleTrue</a></summary>
<br/>Expecting value to be true but was false
</details>

**Comment by yesamer** [comment]
@bncriju Can you please check why the builds are failing?

**Comment by bncriju** [comment]
Checked the build failures and found that this required changes in kogito runtimes repo. https://github.com/apache/incubator-kie-kogito-runtimes/pull/3860 raised

**Review by yesamer — APPROVED** [review]
