### PR TITLE
Fix `spotbug-maven-plugin` usage

### LINKED ISSUE #2279: Fix `spotbug-maven-plugin` usage
Remove the obsolete kie-build-tools dependency from SpotBugs configuration.

Currently, drools defines spotbugs-maven-plugin in 4 submodules: drools-base, drools-compiler, drools-core, and drools-drl-parser.

In build-parent/pom.xml, the plugin used to depend on external org.kie:kie-build-tools:${project.version}. That artifact points to an old non-Apache module and 999-SNAPSHOT is not available anymore.

```
   <groupId>com.github.spotbugs</groupId>
          <artifactId>spotbugs-maven-plugin</artifactId>
          <version>${version.com.github.spotbugs-maven-plugin}</version>
          <dependencies>
            <dependency>
              <groupId>org.kie</groupId>
              <artifactId>kie-build-tools</artifactId>
              <version>${project.version}</version>
            </dependency>
          </dependencies>
```

### PR DESCRIPTION
**Pull request by yesamer**
Closes https://github.com/apache/incubator-kie-issues/issues/2279

Summary of Changes in This PR

- Removed the kie-build-tools dependency from the SpotBugs configuration. It points to an old external module, and version 999-SNAPSHOT is no longer available, which breaks dependency resolution.
- Removed references to missing SpotBugs exclude filter files. These references pointed to files that no longer exist and to the kie-build-tools JAR.
- Upgraded the spotbugs-maven-plugin.
- Fixed a potential NullPointerException detected by the `spotbugs-maven-plugin`.

As a follow-up, we could agree to enable the `spotbugs-maven-plugin` in this project’s submodules (namely `drools-base`, `drools-compiler`, `drools-core`, and `drools-drl-parser` that already declare it) so that the build fails when SpotBugs detects any issues at compile time.
It appears there was already an intention to enable this behavior in the past, since the following configuration is present in the Drools build-parent POM:
```
    <!-- Set to "true" on every project that has no violations. -->
    <spotbugs.failOnViolation>false</spotbugs.failOnViolation>
```

To enable this in specific submodules, we should:

1. In the target submodule’s pom.xml, set spotbugs.failOnViolation to true under <properties>.
2. Keep the spotbugs-maven-plugin execution bound to the verify phase, with both the spotbugs and check goals enabled:

```
<plugin>
  <groupId>com.github.spotbugs</groupId>
  <artifactId>spotbugs-maven-plugin</artifactId>
  <executions>
    <execution>
      <id>spotbugs</id>
      <phase>verify</phase>
      <goals>
        <goal>spotbugs</goal>
        <goal>check</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

### CODE REVIEW

**Review by tkobayas — APPROVED** [review]

**Review by Rikkola — APPROVED** [review]
Worth using.

File: drools-base/src/main/java/org/drools/base/definitions/impl/KnowledgePackageImpl.java [hunk 1]
```diff
@@ -614,7 +614,7 @@ public void wireTypeDeclarations() {
             Class<?> typeClass = null;
             try {
                 typeClass = typeDeclaration.getTypeClass();
-                if (typeClass != null || !typeClass.isPrimitive()) {
+                if (typeClass != null && !typeClass.isPrimitive()) {
```
Comment (gitgabrio) [inline drools-base/src/main/java/org/drools/base/definitions/impl/KnowledgePackageImpl.java:617]: 🤔

File: build-parent/pom.xml [hunk 2]
```diff
@@ -1935,19 +1934,11 @@
...
-              <artifactId>kie-build-tools</artifactId>
-              <version>${project.version}</version>
-            </dependency>
-          </dependencies>
           <configuration>
             <maxRank>6</maxRank>
             <effort>Max</effort>
             <xmlOutput>true</xmlOutput>
             <failOnError>${spotbugs.failOnViolation}</failOnError>
-            <excludeFilterFile>spotbugs-excludes.xml</excludeFilterFile>
```
Comment (gitgabrio) [inline build-parent/pom.xml:1950]: out of curiosity: do you know why that exclude was there and how it behaved ?

File: drools-base/pom.xml [hunk 3]
```diff
@@ -214,9 +214,6 @@
       <plugin>
         <groupId>com.github.spotbugs</groupId>
         <artifactId>spotbugs-maven-plugin</artifactId>
-        <configuration>
```
Comment (gitgabrio) [inline drools-base/pom.xml:217]: out of curiosity: do you know why that exclude was there and how it behaved ?

File: drools-compiler/pom.xml [hunk 4]
```diff
@@ -185,7 +185,6 @@
           <groupId>com.github.spotbugs</groupId>
           <artifactId>spotbugs-maven-plugin</artifactId>
           <configuration>
-            <excludeFilterFile>${project.basedir}/src/main/spotbugs/spotbugs-exclude.xml</excludeFilterFile>
```
Comment (gitgabrio) [inline drools-compiler/pom.xml:188]: Same as above

File: drools-core/pom.xml [hunk 5]
```diff
@@ -225,9 +225,6 @@
       <plugin>
         <groupId>com.github.spotbugs</groupId>
         <artifactId>spotbugs-maven-plugin</artifactId>
-        <configuration>
```
Comment (gitgabrio) [inline drools-core/pom.xml:228]: Same as above

File: drools-drl/drools-drl-parser/pom.xml [hunk 6]
```diff
@@ -105,7 +105,6 @@
                     <groupId>com.github.spotbugs</groupId>
                     <artifactId>spotbugs-maven-plugin</artifactId>
                     <configuration>
-                        <excludeFilterFile>${project.basedir}/src/main/spotbugs/spotbugs-exclude.xml</excludeFilterFile>
```
Comment (gitgabrio) [inline drools-drl/drools-drl-parser/pom.xml:108]: Same as above

File: build-parent/pom.xml (hunk 2 above)
Comment (yesamer) [reply build-parent/pom.xml:1950]: @gitgabrio Yes, you can find that file here --> https://github.com/kiegroup/droolsjbpm-build-bootstrap/tree/main/kie-build-tools/src/main/resources, imported through kie-build-tools dependency
It contains a single rule. 
I didn't find any other reference.

File: drools-base/src/main/java/org/drools/base/definitions/impl/KnowledgePackageImpl.java (hunk 1 above)
Comment (yesamer) [reply drools-base/src/main/java/org/drools/base/definitions/impl/KnowledgePackageImpl.java:617]: That is a bug spotted by spotbugs-maven-plugin

Comment (gitgabrio) [reply drools-base/src/main/java/org/drools/base/definitions/impl/KnowledgePackageImpl.java:617]: Yes, clearly is a bug.. My doubt is that "in theory" it should throw a NPE (the right-side should be executed only when typeClass is `null`, IINW), but it no-one noticed that until now... anyway, good catch 😄

**Review by gitgabrio — APPROVED** [review]

File: drools-base/src/main/java/org/drools/base/definitions/impl/KnowledgePackageImpl.java (hunk 1 above)
Comment (yesamer) [reply drools-base/src/main/java/org/drools/base/definitions/impl/KnowledgePackageImpl.java:617]: @gitgabrio Yes! I think that plugin is quite useful, we should evaluate to enable it some modules
