### PR TITLE
kie-issues#1807: Test Scenario version attribute is not correctly retrieved

### LINKED ISSUE #1807: New Test Scenario Editor saved file can not be run as `mvn clean verify`
This issue belongs to the epic https://github.com/apache/incubator-kie-issues/issues/453. Without this issue the New SceSim editor can not be assumed as matured and Classic SceSim editor needs to be kept.

### Steps to reproduce - existing scesim
1. Please open `dmn-quarkus-example` project, use main branch (https://github.com/apache/incubator-kie-kogito-examples/tree/main/kogito-quarkus-examples/dmn-quarkus-example)
2. run `mvn clean verify` - it will pass 🟢 
3. open the single `.scesim` file using `New SceSim` editor
4. Edit some **given** data cell and save the file
5. run `mvn clean verify` - it will fail, what is kind of expected, however with an error, that indicates that some exception was thrown before test evaluation. in other words, user is not informed what was expected and what was actual result.. User receives just some exception log 🔴 [1]

### Steps to reproduce - fresh scesim
I also struggle to run fresh scesim created from scratch. The tested DMN model is ismple `id` or `print` function, it just takes one input and returns it unchanged. Trying to run a sceism for similar dmn causing [2]

[1]
```
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.816 s <<< FAILURE! -- in testscenario.KogitoScenarioJunitActivatorTest
[ERROR] TrafficViolationTest.#1: Above speed limit: more than 30 km/h -- Time elapsed: 0.524 s <<< ERROR!
org.drools.scenariosimulation.backend.runner.IndexedScenarioException: #1 Above speed limit: more than 30 km/h: Error in GIVEN data (TrafficViolationTest)
        at org.drools.scenariosimulation.backend.runner.AbstractScenarioRunner.defineFailureException(AbstractScenarioRunner.java:144)
        at org.drools.scenariosimulation.backend.runner.AbstractScenarioRunner.singleRunScenario(AbstractScenarioRunner.java:127)
        at org.drools.scenariosimulation.backend.runner.AbstractScenarioRunner.run(AbstractScenarioRunner.java:103)
        at org.kogito.scenariosimulation.runner.KogitoJunitActivator.runChild(KogitoJunitActivator.java:35)
        at org.kogito.scenariosimulation.runner.KogitoJunitActivator.runChild(KogitoJunitActivator.java:26)
Caused by: org.drools.scenariosimulation.backend.runner.ScenarioException: Error in GIVEN data
        at org.drools.scenariosimulation.backend.runner.AbstractRunnerHelper.extractGivenValues(AbstractRunnerHelper.java:164)
        at org.drools.scenariosimulation.backend.runner.AbstractRunnerHelper.run(AbstractRunnerHelper.java:84)
        at org.drools.scenariosimulation.backend.runner.AbstractScenarioRunner.internalRunScenario(AbstractScenarioRunner.java:150)
        at org.drools.scenariosimulation.backend.runner.AbstractScenarioRunner.singleRunScenario(AbstractScenarioRunner.java:124)
        ... 3 more
```

[2]
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.019 s <<< FAILURE! -- in testscenario.KogitoScenarioJunitActivatorTest
[ERROR] testscenario.KogitoScenarioJunitActivatorTest -- Time elapsed: 0.009 s <<< ERROR!
org.drools.scenariosimulation.backend.runner.ScenarioException: Issue on parsing file: /home/jomarko/incubator-kie-kogito-examples/kogito-quarkus-examples/dmn-quarkus-example/target/test-classes/a.scesim
        at org.drools.scenariosimulation.backend.runner.ScenarioJunitActivator.parseFile(ScenarioJunitActivator.java:87)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.drools.scenariosimulation.backend.runner.ScenarioJunitActivator.getChildren(ScenarioJunitActivator.java:64)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
Caused by: java.lang.IllegalArgumentException: Impossible to extract version from the file
        at org.drools.scenariosimulation.backend.util.ScenarioSimulationXMLPersistence.extractVersion(ScenarioSimulationXMLPersistence.java:193)
        at org.drools.scenariosimulation.backend.util.ScenarioSimulationXMLPersistence.migrateIfNecessary(ScenarioSimulationXMLPersistence.java:150)
        at org.drools.scenariosimulation.backend.util.ScenarioSimulationXMLPersistence.unmarshal(ScenarioSimulationXMLPersistence.java:144)
        at org.drools.scenariosimulation.backend.util.ScenarioSimulationXMLPersistence.unmarshal(ScenarioSimulationXMLPersistence.java:136)
        at org.drools.scenariosimulation.backend.runner.ScenarioJunitActivator.parseFile(ScenarioJunitActivator.java:82)
        ... 17 more
```

### PR DESCRIPTION
**Pull request by yesamer**
Closes: https://github.com/apache/incubator-kie-issues/issues/1807

**The problem**
The Test Scenario Engine needs to retrieve the scesim version from the xml root node to apply the correct migration strategy.
The current logic that retrieves that info, uses a regex search, that is too strict: regex patterns with this exact structure 
`<ScenarioSimulationModel version=\"x.x\"` will be found. That means if any other attribute is present in the XML node (or just a single whitespace), the search will fail
eg. `<ScenarioSimulationModel    version=\"x.x\"`  `<ScenarioSimulationModel  namespace="..."  version=\"x.x\"` 

**The solution**
In the same block of code, the DomParser of the xml file is already called. So, I just moved that in the first method line and took advantage of that to retrieve the version in a "safer" way.
This means, the regex search is no longer required, and the version can be safely retrieved disregarding its position in the node and avoiding collision with other possible attributes with the name.

### CODE REVIEW

**Review by gitgabrio — APPROVED** [review]
Thanks for the fix!

**Comment by yesamer** [comment]
@jomarko Can you please review it?

**Comment by yesamer** [comment]
@baldimir Can you please review it?

File: drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/util/ScenarioSimulationXMLPersistenceTest.java [hunk 1]
```diff
@@ -349,24 +353,58 @@ public void migrateIfNecessary() throws Exception {
...
+        assertThat(version).isEqualTo("1.3");
+    }
+
+    @Test
+    public void extractVersionWhenXmlPrologIsPresentAndWithMultipleAttributes4() throws ParserConfigurationException, IOException, SAXException {
+        String version = instance.extractVersion(DOMParserUtil.getDocument("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
+                "<ScenarioSimulationModel attribute2=\"whatever\" attribute1=\"whatever\" version=\"1.4\" />"));
+        assertThat(version).isEqualTo("1.4");
+    }
+
```
Comment (pibizza) [inline drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/util/ScenarioSimulationXMLPersistenceTest.java:437]: I suggest using a parameterized test here - and possibly add an explanation string, to explain the different use cases we are testing.

Comment (yesamer) [reply drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/util/ScenarioSimulationXMLPersistenceTest.java:437]: Thank you @pibizza, that was my first intent, but scesim module is still based on JUnit 4, so I preferred to don't introduce Junit4 Parametrized tests in this class. About the explanation string, which approach do you suggest, please?

Comment (pibizza) [reply drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/util/ScenarioSimulationXMLPersistenceTest.java:437]: @yesamer I would suggest something that describe your use case. In Junit 5 you can add a string for a specific test name.  In this case add some infos in the name and restructure grouping for cases. So you can have a test where you have one entry (version or attribute), one case where you have two entries (version and attribute, times the various possible cases good or bad) and finally one case where you have three entries (version and two attributes, times the two possible values.) I expect order is not relevant, so it should not be present in the tests. at this point the name of the test could be extractXXX_version, extract XXX_version_attribute, extractXXX_version_twoattributes. You can go for different groupings, if you prefer, but that is the general idea.

**Review by pibizza — COMMENTED** [review]
Some comments on tests, as usual.

File: drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/ScenarioSimulationXMLPersistence.java [hunk 2]
```diff
@@ -179,18 +177,17 @@ public String migrateIfNecessary(String rawXml) throws Exception {
...
-
-        if (m.find()) {
-            return m.group(1);
+    public String extractVersion(Document document) {
+        try {
+            return document.getElementsByTagName(SCENARIO_SIMULATION_MODEL_NODE)
+                    .item(0).getAttributes().getNamedItem(VERSION_ATTRIBUTE).getTextContent();
+        } catch (Exception e) {
+            throw new IllegalArgumentException("Impossible to extract version from the file", e);
         }
```
Comment (jomarko) [inline drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/ScenarioSimulationXMLPersistence.java:190]: My only point is only about catching an exception and immediately throwing new one. I believe we could use this approach to avoid `try` `catch` approach. 

https://medium.com/@gurkanucar/how-to-prevent-null-pointer-exceptions-in-java-8d7c894c9bb4

**Review by jomarko — COMMENTED** [review]
Thank you for a PR @yesamer

File: drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/ScenarioSimulationXMLPersistence.java (hunk 2 above)
Comment (yesamer) [reply drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/ScenarioSimulationXMLPersistence.java:190]: Thank you @jomarko, I would argue that the try-catch is present in the approach you shared, It just moved out in another method. In this case, I don't see the need for that, it would create an unnecessary indirection.

Comment (jomarko) [reply drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/ScenarioSimulationXMLPersistence.java:190]: then, I have nothing to share for this PR

**Review by baldimir — APPROVED** [review]
