### PR TITLE
[incubator-kie-drools-6532] Fix ReteDumper for RightInputAdaptorNode

### LINKED ISSUE #6532: Fix ReteDumper for RightInputAdaptorNode
With the recent change of RightInputAdaptorNode, ReteDumper doesn't track sinks of RightInputAdaptorNode.

### PR DESCRIPTION
**Pull request by tkobayas**
- closes https://github.com/apache/incubator-kie-drools/issues/6532

Before the fix, `ReteDumper.dumpRete()` for a rule like this:
```
rule R1
when
    $person: Person()
    exists Address(number > 18) from $person.addresses
then
end
```
results in
```
[EntryPointNode(1) EntryPoint::DEFAULT ]
    [ObjectTypeNode(3)::EntryPoint::DEFAULT objectType=[ClassObjectType class=org.drools.model.codegen.execmodel.domain.Person] expiration=-1ms ]
        [LeftInputAdapterNode(4)]
            [FromNode(5)]
                [TupleToObjectNode(6)]
                    [RightInputAdapterNode(7)]
            [ExistsNode(8) - <source from a subnetwork>]
                [RuleTerminalNode(9): rule=R1]
    [ObjectTypeNode(2)::EntryPoint::DEFAULT objectType=[ClassObjectType class=org.drools.base.reteoo.InitialFactImpl] expiration=-1ms ]
```
See that `[RightInputAdapterNode(7)]` doesn't connect to ` [ExistsNode(8)]`.

After the fix,
```
[EntryPointNode(1) EntryPoint::DEFAULT ]
    [ObjectTypeNode(3)::EntryPoint::DEFAULT objectType=[ClassObjectType class=org.drools.model.codegen.execmodel.domain.Person] expiration=-1ms ]
        [LeftInputAdapterNode(4)]
            [FromNode(5)]
                [TupleToObjectNode(6)]
                    [RightInputAdapterNode(7)]
                        [ExistsNode(8) - <source from a subnetwork>]
                            [RuleTerminalNode(9): rule=R1]
            [ExistsNode(8) - <source from a subnetwork>]
    [ObjectTypeNode(2)::EntryPoint::DEFAULT objectType=[ClassObjectType class=org.drools.base.reteoo.InitialFactImpl] expiration=-1ms ]
```

### CODE REVIEW

File: drools-core/src/main/java/org/drools/core/reteoo/RightInputAdapterNode.java [hunk 1]
```diff
@@ -406,8 +406,7 @@ public boolean equals(Object object) {
 
     @Override
     public String toString() {
-        return "RightInputAdapterNode(" + id + ")[ source="
-               + source + ", associations=" + associations + ", partitionId=" + partitionId + "]";
+        return "[RightInputAdapterNode(" + id + ")]";
```
Comment (tkobayas) [inline drools-core/src/main/java/org/drools/core/reteoo/RightInputAdapterNode.java:409]: Reduced the information in `toString` so the ReteDumper outputs look concise. I hope it's okay as other Nodes' `toString` is similar.

File: drools-model/drools-model-codegen/src/test/java/org/drools/model/codegen/execmodel/ReteDumperTest.java [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+import org.drools.model.codegen.execmodel.domain.Address;
+import org.drools.model.codegen.execmodel.domain.Person;
+import org.junit.jupiter.params.ParameterizedTest;
+import org.junit.jupiter.params.provider.MethodSource;
+import org.kie.api.KieBase;
+import org.kie.api.runtime.KieSession;
+
+import static org.assertj.core.api.Assertions.assertThat;
+
+class ReteDumperTest extends BaseModelTest {
```
Comment (tkobayas) [inline drools-model/drools-model-codegen/src/test/java/org/drools/model/codegen/execmodel/ReteDumperTest.java:39]: Maybe it has been okay without a test for ReteDumper for long time, but I added this to clarify the fix.

File: drools-core/src/main/java/org/drools/core/reteoo/ReteDumper.java [hunk 3]
```diff
@@ -203,6 +203,9 @@ private void dumpNode( BaseNode node, String ident, Set<BaseNode> visitedNodes,
         }
         
         NetworkNode[] sinks = node.getSinks();
+        if (node instanceof RightInputAdapterNode<?> ria) {
+            sinks = new Sink[] { ria.getBetaNode() };
+        }
```
Comment (tkobayas) [inline drools-core/src/main/java/org/drools/core/reteoo/ReteDumper.java:208]: This is the main fix. RightInputAdapterNode has no sink, but actually `betaNode` is its destination.

File: drools-model/drools-model-codegen/src/test/java/org/drools/model/codegen/execmodel/ReteDumper.java [hunk 4]
```diff
@@ -24,7 +24,10 @@
 import java.util.function.BiConsumer;
 import java.util.function.Predicate;
 
+import org.drools.base.common.NetworkNode;
```
[the remark this answers is not in the document]
Comment (tkobayas) [reply drools-model/drools-model-codegen/src/test/java/org/drools/model/codegen/execmodel/ReteDumper.java]: Fixed

**Review by mariofusco — APPROVED** [review]

**Review by Rikkola — APPROVED** [review]
